{
  "hash": "bd87e6cfc155354dbcb6cac4af1c9aa4",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"3.1 Probability Distributions - Solutions\"\nsubtitle: \"307102 Descriptive Statistics for Business | University of Petra\"\ncode-fold: true\ncode-summary: \"Show the code\"\n---\n\n::: {.callout-caution title=\"Instructor copy\"}\nEvery chunk runs. Section headings match the student notebook.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(readxl)\n\nsales <- read_excel(\"../data/supermarket_sales.xlsx\")\n\np_member <- mean(sales$`Customer type` == \"Member\")\n```\n:::\n\n\n# Inline exercises\n\n## Section 2 - Binomial\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_ewallet <- mean(sales$Payment == \"Ewallet\")\np_ewallet\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 0.345\n```\n\n\n:::\n\n```{.r .cell-code}\n# \"Fewer than 4\" means 3 or fewer\npbinom(3, size = 15, prob = p_ewallet)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 0.1831538\n```\n\n\n:::\n:::\n\n\n**The concept being tested** is translating English into an inequality. \"Fewer than\n4\" excludes 4, so it is \"3 or fewer\", so `pbinom(3, ...)`.\n\nStudents who answer `pbinom(4, ...)` have made the single most common error with\ndiscrete distributions. It is worth putting three phrasings on the board and having\nthe class translate each:\n\n| English | Includes the number? | Code |\n|---|---|---|\n| \"at most 4\" | Yes | `pbinom(4, ...)` |\n| \"fewer than 4\" | No | `pbinom(3, ...)` |\n| \"more than 4\" | No | `1 - pbinom(4, ...)` |\n| \"at least 4\" | Yes | `1 - pbinom(3, ...)` |\n\nThe last row catches almost everyone the first time.\n\n## Section 3 - Poisson\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndpois(0, lambda = 2.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 0.082085\n```\n\n\n:::\n:::\n\n\nAbout 8 percent.\n\n**Discussion point.** A complaint-free week is uncommon but unremarkable - it will\nhappen roughly four times a year by chance alone. Worth raising: if a manager\nintroduces a quality initiative and the next week has zero complaints, that is not\nevidence the initiative worked. You would expect that outcome one week in twelve\nregardless.\n\nThis is the intuition behind hypothesis testing, arriving two sections early. It\nlands well here because the arithmetic is simple enough that the logic stands out.\n\n## Section 6 - Why not binomial for call arrivals\n\nCovered in the student notebook's collapsible answer. The two points to draw out:\n\n1. A minute can contain **more than one call**, breaking the two-outcome requirement.\n2. There is **no fixed number of trials** - the answer would change depending on\n   whether you sliced time into minutes, seconds or milliseconds, and a model whose\n   answer depends on an arbitrary choice is wrong.\n\nWorth adding for stronger students: the Poisson *is* the limit of the binomial as\n`n` goes to infinity and `p` goes to zero with `n * p` held constant. The colleague's\ninstinct was not silly, just unfinished.\n\n# Exercise 1 - Binomial\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 25\np <- 0.30\n\n# a. Exactly 8\ndbinom(8, size = n, prob = p)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 0.1650796\n```\n\n\n:::\n\n```{.r .cell-code}\n# b. 10 or more  =  1 - P(9 or fewer)\n1 - pbinom(9, size = n, prob = p)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 0.189436\n```\n\n\n:::\n\n```{.r .cell-code}\n# c. Expected value and standard deviation\ntibble(\n  expected = n * p,\n  sd       = sqrt(n * p * (1 - p))\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 1 × 2\n#>   expected    sd\n#>      <dbl> <dbl>\n#> 1      7.5  2.29\n```\n\n\n:::\n:::\n\n\n**Expected results.** (a) about 0.165; (b) about 0.189; (c) expected 7.5, sd about\n2.29.\n\n**Marking guidance.** Part (b) is the discriminator. \"10 or more\" means\n`1 - pbinom(9, ...)`, not `1 - pbinom(10, ...)`. Students who get (a) right and (b)\nwrong have understood the distribution but not the boundary convention - give partial\ncredit and point them at the translation table above.\n\nPart (c) is worth a follow-up in class: the expected value is **7.5**, which is not a\npossible outcome. Expected values need not be attainable. That surprises students and\nis worth thirty seconds.\n\n# Exercise 2 - Poisson\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlambda <- 3\n\n# a. Exactly 5\ndpois(5, lambda = lambda)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 0.1008188\n```\n\n\n:::\n\n```{.r .cell-code}\n# b. More than 6  =  1 - P(6 or fewer)\n1 - ppois(6, lambda = lambda)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 0.03350854\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# c. Capacity planning table\ntibble(\n  capacity         = 3:9,\n  prob_overwhelmed = round(1 - ppois(3:9, lambda = lambda), 4)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 7 × 2\n#>   capacity prob_overwhelmed\n#>      <int>            <dbl>\n#> 1        3           0.353 \n#> 2        4           0.185 \n#> 3        5           0.0839\n#> 4        6           0.0335\n#> 5        7           0.0119\n#> 6        8           0.0038\n#> 7        9           0.0011\n```\n\n\n:::\n:::\n\n\n**Expected results.** (a) about 0.101; (b) about 0.034.\n\n**Part (c) is where the marks are.** The table itself is mechanical. The\nrecommendation requires judgement, and there is no single right answer - which is the\npoint.\n\nA strong answer names a capacity **and** states the risk it accepts:\n\n> Staffing for capacity 3 - the daily average - leaves us unable to cope on about 35\n> percent of days, which is clearly unacceptable. Capacity 5 brings that down to about\n> 8 percent, and capacity 6 to about 3 percent. I would recommend 5, on the grounds\n> that the step from 4 to 5 removes far more risk than the step from 5 to 6, and a\n> one-in-twelve overflow day can be absorbed by handling a backlog the following\n> morning.\n\n**The exact figures**, for reference when marking: capacity 3 leaves 35.3 percent of\ndays overwhelmed, 4 leaves 18.5 percent, 5 leaves 8.4 percent, 6 leaves 3.4 percent\nand 7 leaves 1.2 percent.\n\nA weak answer picks a number without naming the trade-off, or recommends capacity 9\nwithout acknowledging that near-zero risk is expensive.\n\n::: {.callout-caution title=\"The lesson to land\"}\n**Planning for the average means failing about half the time.**\n\nStudents consistently underestimate this. Ask the class to guess the overflow\nprobability at capacity 3 before showing the table - most say 10 or 20 percent. The\ntrue figure of roughly 35 percent is a genuinely useful surprise.\n:::\n\n# Exercise 3 - Normal\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt_mean <- mean(sales$Total)\nt_sd   <- sd(sales$Total)\n\ntibble(mean = round(t_mean, 2), sd = round(t_sd, 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 1 × 2\n#>    mean    sd\n#>   <dbl> <dbl>\n#> 1  323.  246.\n```\n\n\n:::\n\n```{.r .cell-code}\n# a. Predicted by a normal model\npredicted <- 1 - pnorm(800, mean = t_mean, sd = t_sd)\n\n# b. Actually observed\nactual <- mean(sales$Total > 800)\n\ntibble(\n  predicted = round(predicted, 4),\n  actual    = round(actual, 4)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 1 × 2\n#>   predicted actual\n#>       <dbl>  <dbl>\n#> 1    0.0262  0.058\n```\n\n\n:::\n:::\n\n\n**Expected results.** The normal model predicts roughly 2.5 percent of transactions\nabove 800; the data actually contains roughly 6 percent. **The model\nunder-predicts the tail by more than a factor of two.**\n\n**Part (c) is the exercise.** The section 2 finding that predicts this is\n**right skew**: skewness of `Total` was about 0.89, and the mean (323) sat well above\nthe median (254).\n\nA normal distribution is symmetric. Forcing a symmetric model onto a right-skewed\nvariable makes it systematically underestimate how often large values occur, because\nthe real distribution has a longer right tail than the model allows.\n\n**Why this matters commercially.** If you used this normal model to size anything\nthat depends on large transactions - cash handling, fraud thresholds, high-value\ncustomer programmes - you would be wrong in the expensive direction. The model does\nnot merely have errors; its errors are **biased in a predictable direction**, which\nis far worse.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(sales, aes(x = Total)) +\n  geom_histogram(aes(y = after_stat(density)), bins = 40,\n                 fill = \"#A83296\", colour = \"white\", alpha = 0.85) +\n  stat_function(fun = dnorm, args = list(mean = t_mean, sd = t_sd),\n                colour = \"#1A1A1A\", linewidth = 1) +\n  labs(title = \"Actual transaction totals against a fitted normal curve\",\n       subtitle = \"The curve sits above the data on the left and below it on the right\",\n       x = \"Transaction total\", y = \"Density\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](3.1-Probability-Distributions-SOLUTIONS_files/figure-html/sol_ex3_plot-1.png){width=672}\n:::\n:::\n\n\nThat plot is worth showing in class. The mismatch is visible without any arithmetic,\nand it makes the point better than the numbers do.\n\n# Exercise 4 - Z-scores\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsales |>\n  mutate(\n    total_z  = (Total - mean(Total)) / sd(Total),\n    rating_z = (Rating - mean(Rating)) / sd(Rating)\n  ) |>\n  summarise(\n    max_total     = max(Total),\n    max_total_z   = round(max(total_z), 3),\n    max_rating    = max(Rating),\n    max_rating_z  = round(max(rating_z), 3)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 1 × 4\n#>   max_total max_total_z max_rating max_rating_z\n#>       <dbl>       <dbl>      <dbl>        <dbl>\n#> 1     1043.        2.93         10         1.76\n```\n\n\n:::\n:::\n\n\n**Expected results.** The largest transaction is 1042.65, with a z-score of about\n2.93. The highest rating is 10, with a z-score of about 1.76.\n\n**The answer:** the **transaction** is the more extreme observation. It sits nearly\nthree standard deviations above its mean, while the highest possible rating is less\nthan two above its own.\n\n**Marking guidance.** The comparison is the point, not the arithmetic. Look for the\nstudent explaining *why* z-scores permit a comparison that raw values do not: 1042.65\nand 10 are measured in different units on different scales, and the z-score converts\nboth to the common currency of \"standard deviations from the mean\".\n\n**Extension worth raising.** The maximum rating can never have a large z-score,\nbecause the scale is capped at 10. A bounded variable cannot produce extreme\nstandardised values. This is the same structural point as the Rating outlier exercise\nin section 2, and connecting the two helps it stick.\n\n# Exercise 5 - Choose and justify\n\n| Situation | Distribution | Justification |\n|---|---|---|\n| a. Items in a basket | **Poisson** (or a discrete count model) | Counting events with no fixed maximum and a roughly constant average rate. In practice basket sizes are often over-dispersed, so a negative binomial fits better - but Poisson is the right answer at this level. |\n| b. Queue abandonments in an hour | **Poisson** | Events in a fixed interval of time, no natural upper limit. |\n| c. Daily total revenue | **Normal** | A continuous quantity formed by adding many independent transactions. The Central Limit Theorem (section 3.2) is the formal justification. |\n| d. Returns among the next 40 orders | **Binomial** | A fixed number of trials (40), two outcomes per trial, roughly constant return probability. |\n\n**Marking guidance.** Accept the distribution name only with a justification that\nnames the *structural feature* - fixed number of trials, no upper limit, continuous\nmeasurement, sum of many small effects. A student who writes \"Poisson because it is a\ncount\" has pattern-matched rather than reasoned; counts can be binomial too, and the\ndistinguishing feature is whether there is a fixed `n`.\n\n**Part (a) is deliberately arguable.** In this dataset `Quantity` runs from 1 to 10,\nso there *is* an effective maximum, which makes a binomial defensible. Accept either\nwith good reasoning. Students noticing the ambiguity unprompted are doing exactly what\nyou want.\n\n**Part (c) is the one to dwell on.** Individual transaction totals are clearly *not*\nnormal - that was Exercise 3. But their *sum* over a day is much closer to normal.\nThat distinction between the distribution of individual values and the distribution of\ntheir sum is precisely the Central Limit Theorem, and flagging it here sets up the\nnext notebook.\n\n# Teaching notes\n\n**Where students get stuck.**\n\n1. **Boundary conventions** with `pbinom` and `ppois`. Expect to explain \"at least\"\n   versus \"more than\" more than once. The translation table in the first solution\n   above works well on a slide.\n2. **Choosing between binomial and Poisson.** The reliable test is \"is there a fixed\n   number of trials?\" Teach that question rather than a list of examples.\n3. **`dnorm` versus `pnorm`.** Students reach for `dnorm` when they want a\n   probability. Emphasise that for continuous distributions `dnorm` returns a\n   *density*, not a probability, and that the probability of any exact value is zero.\n   The density can even exceed 1 for a narrow distribution, which is a good way to\n   prove it is not a probability.\n4. **Assuming normality is a property of good data.** Several exercises deliberately\n   show the normal model failing. That is the intended lesson, not a flaw in the\n   dataset.\n\n**Timing.** Sections 1 to 3 fill one 90-minute session; sections 4 to 7 fill a\nsecond. If you have only one session, cut section 7 (simulation) and set it as\nreading - though it is the section students report enjoying most.\n\n**Connecting to the Excel track.** `BINOM.DIST(k, n, p, FALSE)` is `dbinom`;\n`BINOM.DIST(k, n, p, TRUE)` is `pbinom`. `NORM.DIST(x, mean, sd, TRUE)` is `pnorm`;\n`NORM.INV(p, mean, sd)` is `qnorm`. `NORM.S.DIST` and `NORM.S.INV` are `pnorm` and\n`qnorm` with the mean and sd left at their defaults of 0 and 1.\n\nThe printed z-tables in the `Z and T Tables` folder are now optional. Students should\nstill see one once, so they understand what published tables were for, but `pnorm`\nreplaces them entirely and without interpolation error.\n",
    "supporting": [
      "3.1-Probability-Distributions-SOLUTIONS_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}