{
  "hash": "52e8fb778d0920003373696ec58086a2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"2. Descriptive Statistics - Solutions\"\nsubtitle: \"307102 Descriptive Statistics for Business | University of Petra\"\ncode-fold: true\ncode-summary: \"Show the code\"\n---\n\n\n::: {.callout-caution title=\"Instructor copy\"}\nEvery chunk here runs, and every numeric result quoted in the commentary has been\nverified against the standard 1,000-row `supermarket_sales.xlsx`. If your copy of\nthe file has been edited, re-run the notebook and adjust the quoted figures.\n\nSection headings match the student notebook so the two can be read side by side.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(readxl)\nlibrary(moments)\n\nsales <- read_excel(\"../data/supermarket_sales.xlsx\")\n```\n:::\n\n\n---\n\n# Inline Exercises\n\n### Section 2 - Frequency table of Customer type\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsales |>\n  count(`Customer type`) |>\n  mutate(percent = round(n / sum(n) * 100, 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 2 × 3\n#>   `Customer type`     n percent\n#>   <chr>           <int>   <dbl>\n#> 1 Member            501    50.1\n#> 2 Normal            499    49.9\n```\n\n\n:::\n:::\n\n\n**Expected pattern.** Members and Normal customers split close to 50/50.\n\n**Discussion point worth raising.** A near-even split is itself a finding. If the\nchain runs a membership programme, roughly half of transactions being non-member\nmeans half of all sales generate no customer-level data at all. Everything the\nbusiness \"knows\" about its customers is therefore based on a self-selected half -\nand members are, almost by definition, not typical shoppers. This is a good early\nintroduction to **selection bias**, which returns in Part 3.\n\n### Section 3 - Histogram of Rating\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(sales, aes(x = Rating)) +\n  geom_histogram(bins = 20, fill = \"#A83296\", colour = \"white\") +\n  labs(title = \"Distribution of customer ratings\",\n       x = \"Rating\", y = \"Number of customers\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Descriptive-Statistics-SOLUTIONS_files/figure-html/sol_hist-1.png){width=672}\n:::\n:::\n\n\n**Expected pattern.** Not a bell curve. The distribution is broadly flat across the\nmiddle of the scale with a fairly hard floor around 4 and ceiling around 10.\n\n**Why this is a useful teaching moment.** Students arrive expecting everything to be\nnormally distributed, because every textbook picture is. Confronting a flat,\nbounded distribution in week one prevents that assumption from hardening. It also\nsets up section 7 - when the Q-Q plot for `Rating` bends away at both ends,\nstudents have already seen why.\n\nIf a class discussion opens up here, the useful question is: *what would ratings\nlook like if customers only bothered to leave one when they were delighted or\nfurious?* That would give a U-shape, which is what many real review platforms\nactually show. The fact that this dataset does not look like that suggests ratings\nwere collected systematically rather than volunteered.\n\n### Section 4 - Mean and median Rating by product line\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsales |>\n  group_by(`Product line`) |>\n  summarise(\n    transactions  = n(),\n    mean_rating   = round(mean(Rating), 2),\n    median_rating = round(median(Rating), 2)\n  ) |>\n  arrange(desc(mean_rating))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 6 × 4\n#>   `Product line`         transactions mean_rating median_rating\n#>   <chr>                         <int>       <dbl>         <dbl>\n#> 1 Food and beverages              174        7.11          7.3 \n#> 2 Fashion accessories             178        7.03          6.95\n#> 3 Health and beauty               152        7             7.2 \n#> 4 Electronic accessories          170        6.92          6.7 \n#> 5 Sports and travel               166        6.92          6.7 \n#> 6 Home and lifestyle              160        6.84          7\n```\n\n\n:::\n:::\n\n\n**Expected pattern.** All six product lines land within roughly half a point of one\nanother, somewhere near 7.\n\n**The point of the exercise.** Students will want to declare a \"winner\". Push back:\na gap of 0.3 on a 10-point scale, across groups of about 160 transactions each, is\nalmost certainly not a real difference. Ask them what they would need in order to\nclaim it was - and let the answer be unsatisfying for now, because that is exactly\nwhat Part 4 supplies.\n\nNote also that mean and median are close for every product line here, which is what\nyou expect from a roughly symmetric, bounded variable. Contrast with `Total`, where\nthe two diverge noticeably.\n\n### Section 6 - IQR outlier check on Rating\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr_q1  <- quantile(sales$Rating, 0.25)\nr_q3  <- quantile(sales$Rating, 0.75)\nr_iqr <- IQR(sales$Rating)\n\ntibble(\n  q1          = r_q1,\n  q3          = r_q3,\n  iqr         = r_iqr,\n  lower_bound = r_q1 - 1.5 * r_iqr,\n  upper_bound = r_q3 + 1.5 * r_iqr\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 1 × 5\n#>      q1    q3   iqr lower_bound upper_bound\n#>   <dbl> <dbl> <dbl>       <dbl>       <dbl>\n#> 1   5.5   8.5     3           1          13\n```\n\n\n:::\n\n```{.r .cell-code}\nsales |>\n  filter(Rating < r_q1 - 1.5 * r_iqr | Rating > r_q3 + 1.5 * r_iqr) |>\n  nrow()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 0\n```\n\n\n:::\n:::\n\n\n**Expected result: zero outliers.**\n\n**This is the most valuable exercise in the section**, precisely because the answer\nis nothing. Students who predicted \"a few\" need to understand why they were wrong.\n\nQ1 is 5.5 and Q3 is 8.5, so the IQR is 3 and the bounds come out at **1 and 13**.\nThe ratings themselves only run from **4 to 10**. The flagging thresholds sit\noutside the range the scale can even produce, so no value could ever be flagged.\nA bounded variable with a wide interquartile range cannot generate IQR outliers.\nIt is structurally impossible.\n\nTwo conclusions to draw out:\n\n1. **\"No outliers\" does not mean \"clean data\".** It can simply mean the variable\n   has no room to produce extreme values. A student who reports \"I checked for\n   outliers and found none\" without understanding this has learned a ritual, not a\n   method.\n2. **The 1.5 x IQR rule is a convention, not a law.** The 1.5 was chosen by John\n   Tukey because it worked reasonably for roughly normal data. It has no special\n   authority, and it behaves quite differently on bounded, skewed or discrete\n   variables.\n\nContrast with `Total`, where the same rule does flag a handful of points - and\nwhere, as the notebook argues, almost none of them should be deleted. The lower\nbound for `Total` comes out negative, so only the high tail can ever be flagged.\nThat asymmetry is worth pointing out: on a right-skewed variable the IQR rule is\nstructurally one-sided.\n\n### Section 8 - Correlation between Unit price and Rating\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(sales$`Unit price`, sales$Rating)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] -0.008777507\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(sales, aes(x = `Unit price`, y = Rating)) +\n  geom_point(colour = \"#A83296\", alpha = 0.4) +\n  labs(title = \"Unit price against customer rating\",\n       x = \"Unit price\", y = \"Rating\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Descriptive-Statistics-SOLUTIONS_files/figure-html/sol_assoc-1.png){width=672}\n:::\n:::\n\n\n**Expected pattern.** A correlation very close to zero, and a scatterplot that is a\nformless cloud.\n\n**Why the plot matters even when the number is boring.** The notebook's warning is\nthat a near-zero correlation could hide a curved relationship. Here it does not -\nthe plot confirms there is genuinely nothing there. That confirmation is the point.\nStudents should form the habit of plotting *before* concluding, not only when the\nnumber looks interesting.\n\n**The business reading.** How expensive the individual items were has no bearing on\nhow satisfied the customer was. That is worth knowing: it argues against the\nintuition that premium products buy goodwill, and points attention elsewhere -\nservice, queue length, stock availability - for anything that might actually move\nsatisfaction.\n\n---\n\n# Exercise 1 - Branch Performance Report\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsales |>\n  group_by(Branch) |>\n  summarise(\n    transactions  = n(),\n    total_revenue = round(sum(Total), 2),\n    mean_sale     = round(mean(Total), 2),\n    median_sale   = round(median(Total), 2),\n    sd_sale       = round(sd(Total), 2),\n    cv_percent    = round(sd(Total) / mean(Total) * 100, 1)\n  ) |>\n  arrange(desc(total_revenue))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 3 × 7\n#>   Branch transactions total_revenue mean_sale median_sale sd_sale cv_percent\n#>   <chr>         <int>         <dbl>     <dbl>       <dbl>   <dbl>      <dbl>\n#> 1 C               328       110569.      337.        271.    263.       78.1\n#> 2 A               340       106200.      312.        241.    232.       74.2\n#> 3 B               332       106198.      320.        253.    242.       75.8\n```\n\n\n:::\n:::\n\n\n**Expected pattern.** Branch C leads on revenue (about 110,600) with A and B\nessentially tied (about 106,200 each - within two currency units of one another,\nwhich is worth pointing out as a coincidence rather than a finding). Transaction\ncounts run 328 to 340. Mean sale runs about 312 (A) to 337 (C); standard deviations\nrun about 232 to 263.\n\n**Marking guidance.** The table is the easy part. The marks should be for the\ninterpretation, and specifically for whether the student notices that **the\ndifferences are small relative to the spread**. Branch C's mean is about 25 above\nBranch A's, but the standard deviation within each branch is around 245 - so the\ngap between branches is roughly a tenth of the variation inside one branch.\n\nA strong answer says something like: \"Branch C leads on total revenue, but the gap\nis about a tenth of one standard deviation and could easily be chance. On this\nevidence I would not treat any branch as a better performer.\"\n\nA weak answer ranks the branches and stops.\n\n**Extension for stronger students.** Ask why `mean_sale` exceeds `median_sale` in\nevery branch, and what that consistency implies. The answer - that right skew is a\nproperty of retail transaction data generally, not of any one branch - is a genuine\ninsight.\n\n# Exercise 2 - Product Line Profitability\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsales |>\n  group_by(`Product line`) |>\n  summarise(\n    transactions   = n(),\n    total_income   = round(sum(`gross income`), 2),\n    avg_income     = round(mean(`gross income`), 2),\n    avg_basket     = round(mean(Total), 2)\n  ) |>\n  arrange(desc(total_income))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 6 × 5\n#>   `Product line`         transactions total_income avg_income avg_basket\n#>   <chr>                         <int>        <dbl>      <dbl>      <dbl>\n#> 1 Food and beverages              174        2674.       15.4       323.\n#> 2 Sports and travel               166        2625.       15.8       332.\n#> 3 Electronic accessories          170        2588.       15.2       320.\n#> 4 Fashion accessories             178        2586        14.5       305.\n#> 5 Home and lifestyle              160        2565.       16.0       337.\n#> 6 Health and beauty               152        2343.       15.4       324.\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsales |>\n  group_by(`Product line`) |>\n  summarise(avg_income = round(mean(`gross income`), 2)) |>\n  arrange(desc(avg_income))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 6 × 2\n#>   `Product line`         avg_income\n#>   <chr>                       <dbl>\n#> 1 Home and lifestyle           16.0\n#> 2 Sports and travel            15.8\n#> 3 Health and beauty            15.4\n#> 4 Food and beverages           15.4\n#> 5 Electronic accessories       15.2\n#> 6 Fashion accessories          14.5\n```\n\n\n:::\n:::\n\n\n**Expected pattern - and it works out beautifully here.** **Food and beverages**\ntops total gross income (about 2,674). But **Home and lifestyle** tops average\nincome per transaction (about 16.0) while sitting **fifth of six** on total income,\nbecause it has the fewest transactions after Health and beauty.\n\nSo the two questions give genuinely different answers, which is exactly the point of\nthe exercise.\n\n**The concept being tested.** Total income is a product of two things: how much\neach sale earns, and how many sales there are. A line can lead on total by selling\na great deal at a modest margin, or by selling little at a high one. These call for\nopposite management responses:\n\n- **High volume, low margin** - protect the volume. Do not raise prices casually,\n  and make sure it is always in stock.\n- **Low volume, high margin** - growth potential. Ask why volume is low. Is it\n  shelf position, awareness, or genuinely limited demand?\n\n**Marking guidance.** Full credit requires the student to compute both figures\n*and* to say why the distinction changes what a manager should do. A student who\nproduces both columns without connecting them to a decision has done the\narithmetic but missed the analysis.\n\n**Worth flagging in class.** In this dataset `gross income` is **exactly 4.7619\npercent of `Total` for every single row** - the `gross margin percentage` column is\na constant. Margin therefore does not vary by product line at all, and the\ndifferences in average income per transaction are purely differences in **basket\nsize**, not in profitability.\n\nThis is worth saying out loud, because it means the exercise's apparent finding is\npartly an artefact of how the data was generated. Students can verify it in one\nline:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrange(sales$`gross income` / sales$Total * 100)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 4.761905 4.761905\n```\n\n\n:::\n:::\n\n\nRecognising when a dataset cannot answer the question you are asking is a more\nadvanced skill than computing the answer, and this is a safe place to practise it.\nA good follow-up question: *what column would we need in order to compare true\nprofitability across product lines?*\n\n# Exercise 3 - Satisfaction By Payment Method\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsales |>\n  group_by(Payment) |>\n  summarise(\n    transactions  = n(),\n    mean_rating   = round(mean(Rating), 2),\n    median_rating = round(median(Rating), 2),\n    sd_rating     = round(sd(Rating), 2)\n  ) |>\n  arrange(desc(mean_rating))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 3 × 5\n#>   Payment     transactions mean_rating median_rating sd_rating\n#>   <chr>              <int>       <dbl>         <dbl>     <dbl>\n#> 1 Credit card          311        7              7        1.75\n#> 2 Cash                 344        6.97           6.9      1.69\n#> 3 Ewallet              345        6.95           6.9      1.73\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(sales, aes(x = Payment, y = Rating)) +\n  geom_boxplot(fill = \"#A83296\", alpha = 0.7) +\n  labs(title = \"Customer rating by payment method\",\n       x = \"Payment method\", y = \"Rating\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Descriptive-Statistics-SOLUTIONS_files/figure-html/sol_ex3b-1.png){width=672}\n:::\n:::\n\n\n**Expected pattern.** Credit card 7.00, Cash 6.97, Ewallet 6.95 - a total spread of\n**0.05** - with standard deviations near 1.7 and three boxplots that overlap almost\ncompletely.\n\n**The answer to \"do the differences matter?\" is no**, and this is about as clear-cut\nas it gets: the gap between the best and worst payment method is one thirty-fifth of\nthe variation within any one of them. The boxplot makes that obvious at a glance.\nThis is the exercise where the visual does the arguing.\n\n**Marking guidance.** Look for the student comparing the size of the difference\nbetween groups against the size of the variation within groups. A 0.05 gap between\ngroups whose internal standard deviation is 1.7 is nothing at all. Students who articulate\nthat comparison - even informally, as \"the boxes overlap far too much\" - have\ngrasped the intuition behind every hypothesis test in Part 4.\n\n**Useful follow-up question for discussion.** If the business had run this analysis\non 50 transactions instead of 1,000, would they have been more or less likely to\nfind a \"difference\"? Smaller samples produce noisier group means, so more likely -\nand that is precisely how spurious findings get into business reports.\n\n# Exercise 4 - Shape Investigation: Unit Price\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsales |>\n  summarise(\n    mean_price   = round(mean(`Unit price`), 2),\n    median_price = round(median(`Unit price`), 2),\n    sd_price     = round(sd(`Unit price`), 2),\n    skewness     = round(skewness(`Unit price`), 3),\n    kurtosis     = round(kurtosis(`Unit price`), 3),\n    excess_kurt  = round(kurtosis(`Unit price`) - 3, 3)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 1 × 6\n#>   mean_price median_price sd_price skewness kurtosis excess_kurt\n#>        <dbl>        <dbl>    <dbl>    <dbl>    <dbl>       <dbl>\n#> 1       55.7         55.2     26.5    0.007     1.78       -1.22\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(sales, aes(x = `Unit price`)) +\n  geom_histogram(bins = 30, fill = \"#A83296\", colour = \"white\") +\n  geom_vline(aes(xintercept = mean(`Unit price`)),\n             colour = \"#1A1A1A\", linewidth = 1) +\n  geom_vline(aes(xintercept = median(`Unit price`)),\n             colour = \"#1A1A1A\", linewidth = 1, linetype = \"dashed\") +\n  labs(title = \"Unit price, with mean (solid) and median (dashed)\",\n       x = \"Unit price\", y = \"Frequency\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Descriptive-Statistics-SOLUTIONS_files/figure-html/sol_ex4b-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(sales, aes(sample = `Unit price`)) +\n  stat_qq(colour = \"#A83296\", alpha = 0.5) +\n  stat_qq_line(colour = \"#1A1A1A\") +\n  labs(title = \"Q-Q plot: Unit price\",\n       x = \"Theoretical normal quantiles\", y = \"Observed unit price\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Descriptive-Statistics-SOLUTIONS_files/figure-html/sol_ex4c-1.png){width=672}\n:::\n:::\n\n\n**Expected pattern.** Skewness close to zero, mean and median nearly identical, a\nroughly flat histogram, and a Q-Q plot with a pronounced S-shape.\n\n**Model answer.**\n\n> Unit price is essentially symmetric - skewness is near zero and the mean and\n> median are almost the same, so neither is distorted by a tail. But it is not\n> normal. The histogram is close to flat rather than bell-shaped, and the excess\n> kurtosis is clearly negative, meaning far less of the data sits in the tails than\n> a normal distribution would put there. The Q-Q plot confirms this with an S-shape:\n> the observed values run out of room at both ends because prices are bounded at\n> roughly 10 and 100. Since the distribution is symmetric, the mean and median are\n> equally good summaries, and the mean is conventional.\n\n**The trap this exercise sets.** Students frequently equate \"symmetric\" with\n\"normal\". Unit price is the counterexample: symmetric, and emphatically not normal.\nA uniform distribution is perfectly symmetric and has nothing in common with a bell\ncurve. If a student writes \"skewness is near zero therefore the data is normal\",\nthat is the misconception to correct.\n\n**On the kurtosis figure.** Encourage students to report the excess value\n(subtracting 3) so it is comparable with Excel and with published figures, but to\nsay which convention they are using. Unstated conventions are how numbers get\nmisread.\n\n# Exercise 5 - A Question Of Your Own\n\nOpen-ended. Below are three worked examples at increasing levels of sophistication,\nusable as exemplars or as a marking reference.\n\n### Level 1 - Descriptive, competently done\n\n*Does the busiest branch also have the happiest customers?*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsales |>\n  group_by(Branch) |>\n  summarise(\n    transactions = n(),\n    avg_rating   = round(mean(Rating), 2)\n  ) |>\n  arrange(desc(transactions))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 3 × 3\n#>   Branch transactions avg_rating\n#>   <chr>         <int>      <dbl>\n#> 1 A               340       7.03\n#> 2 B               332       6.82\n#> 3 C               328       7.07\n```\n\n\n:::\n:::\n\n\nCorrect, clearly presented, but asks little of the data.\n\n### Level 2 - Two variables combined\n\n*Do members spend more than non-members, and is the difference consistent across\nbranches?*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsales |>\n  group_by(Branch, `Customer type`) |>\n  summarise(\n    transactions = n(),\n    avg_spend    = round(mean(Total), 2),\n    .groups = \"drop\"\n  ) |>\n  pivot_wider(names_from = `Customer type`, values_from = c(transactions, avg_spend))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 3 × 5\n#>   Branch transactions_Member transactions_Normal avg_spend_Member\n#>   <chr>                <int>               <int>            <dbl>\n#> 1 A                      167                 173             321.\n#> 2 B                      165                 167             325.\n#> 3 C                      169                 159             337.\n#> # ℹ 1 more variable: avg_spend_Normal <dbl>\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(sales, aes(x = Branch, y = Total, fill = `Customer type`)) +\n  geom_boxplot(alpha = 0.8) +\n  scale_fill_manual(values = c(\"#A83296\", \"#D070D0\")) +\n  labs(title = \"Spend by customer type within each branch\",\n       x = \"Branch\", y = \"Transaction total\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Descriptive-Statistics-SOLUTIONS_files/figure-html/sol_ex5b2-1.png){width=672}\n:::\n:::\n\n\nBetter. It asks whether a pattern holds up when you split it further - the\nbeginning of controlling for a third variable, which is what Part 5 formalises.\n\n### Level 3 - Aware of its own limitations\n\n*Which hour of the day generates the most revenue, and should staffing follow it?*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsales |>\n  # readxl may read Time as a date-time or as text depending on the file.\n  # Pulling the digits before the first colon works either way.\n  mutate(hour = as.numeric(str_extract(as.character(Time), \"\\\\d{1,2}(?=:)\"))) |>\n  group_by(hour) |>\n  summarise(\n    transactions  = n(),\n    total_revenue = round(sum(Total), 2),\n    avg_sale      = round(mean(Total), 2)\n  ) |>\n  arrange(desc(total_revenue))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 11 × 4\n#>     hour transactions total_revenue avg_sale\n#>    <dbl>        <int>         <dbl>    <dbl>\n#>  1    19          113        39700.     351.\n#>  2    13          103        34723.     337.\n#>  3    10          101        31421.     311.\n#>  4    15          102        31180.     306.\n#>  5    14           83        30828.     371.\n#>  6    11           90        30377.     338.\n#>  7    12           89        26066.     293.\n#>  8    18           93        26030.     280.\n#>  9    16           77        25226.     328.\n#> 10    17           74        24445.     330.\n#> 11    20           75        22970.     306.\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsales |>\n  # readxl may read Time as a date-time or as text depending on the file.\n  # Pulling the digits before the first colon works either way.\n  mutate(hour = as.numeric(str_extract(as.character(Time), \"\\\\d{1,2}(?=:)\"))) |>\n  group_by(hour) |>\n  summarise(total_revenue = sum(Total)) |>\n  ggplot(aes(x = hour, y = total_revenue)) +\n  geom_col(fill = \"#A83296\") +\n  labs(title = \"Revenue by hour of day\",\n       x = \"Hour\", y = \"Total revenue\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Descriptive-Statistics-SOLUTIONS_files/figure-html/sol_ex5c2-1.png){width=672}\n:::\n:::\n\n\nThe strongest answers will note that revenue per hour reflects **when the shop is\nopen and staffed**, not raw demand - a quiet hour might be quiet because there are\nno tills open. The data cannot distinguish these, so it cannot by itself justify a\nstaffing change. Recognising that limitation is worth more than the chart.\n\n**Marking guidance for Exercise 5.**\n\n| Band | What it looks like |\n|---|---|\n| Excellent | Non-obvious question; correct method; interprets in business terms; states what the data cannot tell you |\n| Good | Sensible question; correct method; clear interpretation |\n| Adequate | Question answered correctly but restates a worked example; interpretation thin |\n| Weak | Code runs but no interpretation, or a conclusion the output does not support |\n\nThe most common failure is a technically flawless pipeline with no sentence saying\nwhat it means. Weight the interpretation heavily, and say so in advance.\n\n# Teaching Notes\n\n**Where students get stuck, in order of frequency.**\n\n1. **Backticks.** Column names with spaces cause more failed chunks than everything\n   else combined. Say it in the first five minutes and put it on the board.\n2. **`=` versus `==`.** Inside `filter()`, a single equals sign produces an error\n   whose message does not obviously point at the cause.\n3. **`+` versus `|>`.** Inside `ggplot()` layers join with `+`. Outside it, steps\n   join with `|>`. Mixing them is near-universal in week one.\n4. **Forgetting `library(tidyverse)`** after restarting R, then meeting\n   `could not find function \"filter\"` and assuming the installation is broken.\n5. **Case sensitivity.** `Rating` works; `rating` does not. Recommend running\n   `names(sales)` and copying from the output.\n\n**Timing.** Sections 1 to 4 comfortably fill one 90-minute session. Sections 5 to 8\nfill a second. Section 9 works well as a short demonstration at the start of the\nPart 3 session, where it lands better than at the end of Part 1.\n\n**If you are short of time**, section 9 is the one to cut, since Part 3 covers the\nsame ground formally. Do not cut the Q-Q plots in section 7 - Part 4 depends on\nstudents being able to read one.\n\n**Connecting to the Excel track.** Students who did the Excel version may want a\nmapping. The main correspondences: `mean` for `AVERAGE`, `sd` for `STDEV.S`,\n`quantile` for `PERCENTILE.INC`, `cor` for `CORREL`, `count` for a PivotTable, and\n`group_by` plus `summarise` for a PivotTable with a row field. Flag the skewness\nand kurtosis conventions, which differ as described in the student notebook.\n",
    "supporting": [
      "Descriptive-Statistics-SOLUTIONS_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}