{
  "hash": "cc6a4df835b08b98b67013ef00866061",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"3.3 Hypothesis Testing - Solutions\"\nsubtitle: \"307102 Descriptive Statistics for Business | University of Petra\"\ncode-fold: true\ncode-summary: \"Show the code\"\n---\n\n::: {.callout-caution title=\"Instructor copy\"}\nEvery chunk runs.\n\n**A warning about this notebook before you teach it.** Almost every test in these\nexercises comes back **non-significant**. That is not a defect in the dataset - it is\nthe most valuable feature of it.\n\nStudents arrive expecting statistics to produce findings. What it mostly produces is\nthe disciplined conclusion that an apparent pattern is indistinguishable from noise.\nA course where every test is significant teaches students to expect significance, and\nthey then go and find it whether it is there or not.\n\nSay this out loud in the first session. Otherwise students conclude they have done\nsomething wrong.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(readxl)\nlibrary(car)\nlibrary(effectsize)\n\nsales <- read_excel(\"../data/supermarket_sales.xlsx\")\n```\n:::\n\n\n# Inline exercises\n\n## Section 8 - The manager running 20 tests\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(\n  n_tests = c(1, 5, 10, 20, 50),\n  prob_at_least_one_false_positive = round(1 - 0.95^c(1, 5, 10, 20, 50), 3)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 5 × 2\n#>   n_tests prob_at_least_one_false_positive\n#>     <dbl>                            <dbl>\n#> 1       1                            0.05 \n#> 2       5                            0.226\n#> 3      10                            0.401\n#> 4      20                            0.642\n#> 5      50                            0.923\n```\n\n\n:::\n:::\n\n\n**The point.** With 20 tests there was about a 64 percent chance of at least one\n\"significant\" result even if every branch were identical. A single p = 0.04 out of 20\ntests is exactly what pure noise looks like.\n\n**What he should do.** Either correct for the number of tests:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Twenty p-values, one of which is 0.04\nexample_pvals <- c(0.04, runif(19, 0.06, 0.99))\n\nround(min(p.adjust(example_pvals, method = \"holm\")), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 0.8\n```\n\n\n:::\n:::\n\n\nAfter correction the smallest adjusted p-value is nowhere near significance.\n\nOr - better - treat the finding as a **hypothesis to test on fresh data**. A result\nthat survives on new data is a finding; one that does not was noise. This is the\ndistinction between exploratory and confirmatory analysis, and it is worth naming\nexplicitly.\n\n# Exercise 1 - One-sample t-test\n\n**Hypotheses.**\n\n- H0: the population mean rating equals 7.0\n- H1: the population mean rating does not equal 7.0\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(sales$Rating, mu = 7.0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tOne Sample t-test\n#> \n#> data:  sales$Rating\n#> t = -0.50233, df = 999, p-value = 0.6155\n#> alternative hypothesis: true mean is not equal to 7\n#> 95 percent confidence interval:\n#>  6.866054 7.079346\n#> sample estimates:\n#> mean of x \n#>    6.9727\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(\n  sample_mean = round(mean(sales$Rating), 4),\n  p_value     = round(t.test(sales$Rating, mu = 7)$p.value, 4)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 1 × 2\n#>   sample_mean p_value\n#>         <dbl>   <dbl>\n#> 1        6.97   0.616\n```\n\n\n:::\n:::\n\n\n**Expected result.** The sample mean is about 6.97, and the p-value is large - nowhere\nnear 0.05. **Fail to reject H0.**\n\n**Model conclusion.**\n\n> Average customer satisfaction is 6.97 out of 10. This is not significantly different\n> from management's claimed figure of 7.0, so the data provides no evidence against it.\n\n**Marking guidance.** Three things to look for.\n\nThe student must write **\"fail to reject\"**, not **\"accept\"**. We have not shown the\nmean is 7.0; we have shown the data is consistent with it, which is weaker.\n\nThe confidence interval should be mentioned. It contains 7.0, which is the same\nconclusion viewed from a different angle - and reinforces that the test and the\ninterval are one calculation, not two.\n\nThe conclusion must be in **business language**. \"t = -0.50, p = 0.617\" is not a\nconclusion. A manager cannot act on it.\n\n::: {.callout-caution title=\"Discussion prompt\"}\nAsk: *would we have rejected if management had claimed 7.2?*\n\nRunning it takes ten seconds and the answer is yes. That makes the point that a\nhypothesis test evaluates **a specific claim**, not the data in general - and that\n\"not significant\" is always relative to what was proposed.\n:::\n\n# Exercise 2 - Two-sample with assumptions and effect size\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsales |>\n  group_by(Gender) |>\n  summarise(\n    n          = n(),\n    mean_spend = round(mean(Total), 2),\n    sd_spend   = round(sd(Total), 2)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 2 × 4\n#>   Gender     n mean_spend sd_spend\n#>   <chr>  <int>      <dbl>    <dbl>\n#> 1 Female   501       335.     249.\n#> 2 Male     499       311.     242.\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(sales, aes(x = Gender, y = Total)) +\n  geom_boxplot(fill = \"#A83296\", alpha = 0.7) +\n  labs(title = \"Transaction value by gender\", x = NULL, y = \"Transaction total\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](3.3-Hypothesis-Testing-SOLUTIONS_files/figure-html/sol_ex2_plot-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nleveneTest(Total ~ factor(Gender), data = sales)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Levene's Test for Homogeneity of Variance (center = median)\n#>        Df F value Pr(>F)\n#> group   1  0.9055 0.3415\n#>       998\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(sales, aes(sample = Total)) +\n  stat_qq(colour = \"#A83296\", alpha = 0.4) +\n  stat_qq_line(colour = \"#1A1A1A\") +\n  facet_wrap(~ Gender) +\n  labs(title = \"Q-Q plots by gender\", x = \"Theoretical\", y = \"Observed\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](3.3-Hypothesis-Testing-SOLUTIONS_files/figure-html/sol_ex2_qq-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(Total ~ Gender, data = sales)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tWelch Two Sample t-test\n#> \n#> data:  Total by Gender\n#> t = 1.5642, df = 997.34, p-value = 0.1181\n#> alternative hypothesis: true difference in means between group Female and group Male is not equal to 0\n#> 95 percent confidence interval:\n#>  -6.186481 54.799346\n#> sample estimates:\n#> mean in group Female   mean in group Male \n#>             335.0957             310.7892\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncohens_d(Total ~ Gender, data = sales)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Cohen's d |        95% CI\n#> -------------------------\n#> 0.10      | [-0.03, 0.22]\n#> \n#> - Estimated using pooled SD.\n```\n\n\n:::\n:::\n\n\n**Expected results.** Female customers average **335.10** against **310.79** for male\ncustomers, on 501 and 499 transactions. Levene's test gives p = 0.34. The t-test gives\n**p = 0.118**, and **Cohen's d is 0.099**.\n\n**The model answer.**\n\n> Female customers spend about 335 per transaction against about 311 for male\n> customers. Levene's test finds no evidence of unequal variances, and while the Q-Q\n> plots show the right skew we identified in section 2, the sample of roughly 500 per\n> group makes the t-test robust to it via the Central Limit Theorem.\n>\n> The difference is not statistically significant (p = 0.118), and Cohen's d of 0.099\n> is well below even the conventional \"small\" threshold of 0.2. Even if it were\n> significant, a gap of this size explains almost none of the variation in what\n> customers spend, and would not justify a gender-differentiated marketing strategy.\n\n**Marking guidance.** Full credit requires the student to report the effect size **and\nuse it**. A student who reports d = 0.1 and then recommends a strategy has computed\nthe number without understanding it.\n\nThe strongest answers note that the conclusion would be the same either way: the effect\nis too small to act on regardless of which side of 0.05 the p-value lands. That is\nexactly the reasoning this section is trying to instil.\n\n# Exercise 3 - ANOVA\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsales |>\n  group_by(Branch) |>\n  summarise(\n    n         = n(),\n    mean_total = round(mean(Total), 2),\n    sd_total   = round(sd(Total), 2)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 3 × 4\n#>   Branch     n mean_total sd_total\n#>   <chr>  <int>      <dbl>    <dbl>\n#> 1 A        340       312.     232.\n#> 2 B        332       320.     242.\n#> 3 C        328       337.     263.\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbranch_model <- aov(Total ~ Branch, data = sales)\n\nsummary(branch_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>              Df   Sum Sq Mean Sq F value Pr(>F)\n#> Branch        2   106988   53494   0.885  0.413\n#> Residuals   997 60292151   60474\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\neta_squared(branch_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # Effect Size for ANOVA\n#> \n#> Parameter |     Eta2 |       95% CI\n#> -----------------------------------\n#> Branch    | 1.77e-03 | [0.00, 1.00]\n#> \n#> - One-sided CIs: upper bound fixed at [1.00].\n```\n\n\n:::\n:::\n\n\n**Expected results.** Branch means run roughly 312, 320 and 337. The ANOVA p-value is\nabove 0.05, and eta-squared is tiny - on the order of 0.001 to 0.002.\n\n**Conclusion: fail to reject.** There is no evidence the three branches differ in\naverage transaction value.\n\n**The interpretation that earns the marks.** Eta-squared of about 0.002 means branch\nexplains roughly **0.2 percent** of the variation in transaction value. Even if the\ntest had been significant, 99.8 percent of why transactions differ has nothing to do\nwith which branch they occurred in.\n\nThat is a far more useful sentence for a manager than \"p = 0.23\".\n\n**On TukeyHSD.** The exercise says to run it *if the result is significant*. It is\nnot, so a student who runs it anyway has missed a step in the logic - though running it\nto see that all intervals contain zero is a reasonable way to confirm the conclusion.\nAccept it with a note.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Shown for completeness - every interval contains zero\nTukeyHSD(branch_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>   Tukey multiple comparisons of means\n#>     95% family-wise confidence level\n#> \n#> Fit: aov(formula = Total ~ Branch, data = sales)\n#> \n#> $Branch\n#>          diff       lwr      upr     p adj\n#> B-A  7.518475 -37.01754 52.05449 0.9171073\n#> C-A 24.745684 -19.92752 69.41889 0.3953886\n#> C-B 17.227209 -27.70950 62.16391 0.6405275\n```\n\n\n:::\n:::\n\n\n::: {.callout-caution title=\"Worth connecting back\"}\nIn section 2, Exercise 1, students computed these same branch means and were asked\nwhether the differences mattered. The strong answers said no, informally, by comparing\nthe gap between branches with the spread inside them.\n\nThis ANOVA is the formal version of that intuition. Making the connection explicit is\nworth two minutes - it shows the course is one argument rather than a sequence of\ntechniques.\n:::\n\n# Exercise 4 - Chi-square\n\n\n::: {.cell}\n\n```{.r .cell-code}\nct <- table(sales$`Customer type`, sales$`Product line`)\n\nct\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>         \n#>          Electronic accessories Fashion accessories Food and beverages\n#>   Member                     78                  86                 94\n#>   Normal                     92                  92                 80\n#>         \n#>          Health and beauty Home and lifestyle Sports and travel\n#>   Member                73                 83                87\n#>   Normal                79                 77                79\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresult <- chisq.test(ct)\n\n# Assumption check: all expected counts should be at least 5\nround(result$expected, 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>         \n#>          Electronic accessories Fashion accessories Food and beverages\n#>   Member                   85.2                89.2               87.2\n#>   Normal                   84.8                88.8               86.8\n#>         \n#>          Health and beauty Home and lifestyle Sports and travel\n#>   Member              76.2               80.2              83.2\n#>   Normal              75.8               79.8              82.8\n```\n\n\n:::\n\n```{.r .cell-code}\nmin(result$expected)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 75.848\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresult\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tPearson's Chi-squared test\n#> \n#> data:  ct\n#> X-squared = 3.325, df = 5, p-value = 0.65\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(result$residuals, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>         \n#>          Electronic accessories Fashion accessories Food and beverages\n#>   Member                  -0.78               -0.34               0.73\n#>   Normal                   0.78                0.34              -0.73\n#>         \n#>          Health and beauty Home and lifestyle Sports and travel\n#>   Member             -0.36               0.32              0.42\n#>   Normal              0.36              -0.32             -0.42\n```\n\n\n:::\n:::\n\n\n**Expected results.** All expected counts comfortably exceed 5, so the assumption\nholds. The p-value is above 0.05, and no residual approaches the rough threshold of\nplus or minus 2.\n\n**Conclusion: fail to reject.** There is no evidence that members and non-members buy\nfrom different product lines.\n\n**Why the residual step matters even when the test is non-significant.** It confirms\nthat no single cell is driving anything, which is a stronger statement than the\np-value alone. Had one residual been 3.5 with an overall p of 0.06, that would be worth\ninvestigating on new data.\n\n**Marking guidance.** The assumption check is not optional and should carry marks.\nStudents who run `chisq.test()` without examining `$expected` have skipped the one step\nthat determines whether the p-value means anything.\n\n**A commercially useful reading.** \"Membership does not predict what people buy\" is a\ngenuine finding with an operational consequence: the loyalty programme should not be\nused to target product-specific promotions, because members are not a distinct\npurchasing segment. Encourage students to state the *business* implication of a null\nresult rather than treating it as a non-answer.\n\n# Exercise 5 - Choose and defend\n\n| Question | Test | Justification |\n|---|---|---|\n| a. Morning versus afternoon ratings | **Independent two-sample t-test** | Numeric outcome, two independent groups of different customers. If time were split into three or more periods, ANOVA instead. |\n| b. Proportion of members across three branches | **Chi-square test of independence** | Two categorical variables - branch and customer type - and counts, not means. |\n| c. Rating before and after training, same 40 customers | **Paired t-test** | Each customer is measured twice, so the two samples are not independent. |\n| d. Gross income across six product lines | **One-way ANOVA** | Numeric outcome across more than two groups. |\n\n**Marking guidance.** The justification carries the marks, and it must name the\n*structural* feature: how many groups, whether the outcome is numeric or categorical,\nand whether the observations are paired.\n\n**Part (c) is the discriminator.** A student who says \"two-sample t-test\" has missed\nthe pairing. This is worth dwelling on because it is the error with real consequences -\nanalysing paired data as independent throws away statistical power and can turn a real\neffect into a null result. The demonstration in section 3 of the student notebook shows\nexactly how large that loss can be.\n\n**Part (b) catches a different error.** Some students propose a t-test because \"we are\ncomparing proportions and proportions are numbers\". The outcome is *membership*, which\nis categorical; the proportion is a summary of it, not the raw measurement. A\n`prop.test()` comparing two branches would be defensible, but with three branches\nchi-square is the natural choice.\n\n# Teaching notes\n\n**Where students get stuck.**\n\n1. **Interpreting the p-value.** Expect \"the probability the null is true\" from\n   students who can recite the correct definition. The phrasing that helps: *a p-value\n   assumes the null is true - it cannot also tell you whether it is.*\n2. **\"Accept the null.\"** Correct this every single time, from week one. The habit\n   forms early or not at all.\n3. **Believing non-significant means no effect.** It means insufficient evidence, which\n   may simply reflect a small sample. Distinguishing \"no effect\" from \"no evidence of\n   an effect\" is a genuinely difficult idea and needs repetition.\n4. **Skipping assumption checks** because the test runs without complaining. R will\n   happily return a p-value from a badly violated test.\n5. **The formula notation `y ~ x`.** Unfamiliar at first, but it recurs in ANOVA and\n   regression, so time spent here pays off twice.\n\n**Timing.** Sections 1 to 5 fill one 90-minute session - the logic, t-tests,\nassumptions and effect size. Sections 6 to 8 fill a second - ANOVA, chi-square and test\nselection. Section 5 is the one not to cut.\n\n**The demonstration to run live.** The effect size table in section 5, where a trivial\ndifference becomes significant as `n` grows. Run it in front of the class and let them\nwatch the p-value fall while the effect size does not move. Nothing else makes the\npoint as economically.\n\n**Connecting to the Excel track.** `T.TEST(range1, range2, tails, type)` covers the\nt-tests, with `type` 1, 2 and 3 for paired, equal-variance and unequal-variance. Excel's\nAnalysis ToolPak has single-factor ANOVA. `CHISQ.TEST(observed, expected)` requires you\nto build the expected table yourself, which `chisq.test()` does automatically.\n\nExcel has **no built-in effect size**, no Levene's test, no Shapiro-Wilk, and no\npost-hoc correction. That gap is the clearest argument in the whole course for teaching\nthis material in R.\n",
    "supporting": [
      "3.3-Hypothesis-Testing-SOLUTIONS_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}