{
  "hash": "4ecf72a6429aa05f8d0db97020a03006",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"3.2 Estimation and Confidence Intervals\"\nsubtitle: \"307102 Descriptive Statistics for Business | University of Petra\"\n---\n\n## New R this week\n\n| Function | What it does | Why a business needs it |\n|---|---|---|\n| `sample()` | Draws a random subset of rows or values | Simulating what a survey would have found |\n| `replicate()` | Repeats an expression many times | Building a sampling distribution from scratch |\n| `qt()` | Critical value from the t-distribution | The multiplier in a confidence interval |\n| `t.test()` | Confidence interval for a mean, in one line | The everyday tool |\n| `prop.test()` | Confidence interval for a proportion | \"What share of customers are members?\" |\n\n## Objectives\n\nBy the end of this notebook you will be able to:\n\n- Explain the difference between a population and a sample, and between a parameter and a statistic\n- Describe what a sampling distribution is, and demonstrate the Central Limit Theorem by simulation\n- Calculate and interpret the standard error of the mean\n- Build a confidence interval for a mean by hand and with `t.test()`\n- Build a confidence interval for a proportion\n- Explain what a 95 percent confidence interval does and does not mean\n- Work out the sample size needed for a target margin of error\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(readxl)\n\nset.seed(2024)\n\nsales <- read_excel(\"../data/supermarket_sales.xlsx\")\n```\n:::\n\n\n# 1. Population, sample, parameter, statistic\n\nFour words that get confused constantly. Getting them straight is most of the battle.\n\n| Term | Meaning | Notation | Example |\n|---|---|---|---|\n| **Population** | Every member of the group you care about | - | All transactions the chain will ever process |\n| **Sample** | The subset you actually observed | - | Our 1,000 transactions |\n| **Parameter** | A number describing the **population** | Greek: mu, sigma, p | The true average transaction value |\n| **Statistic** | A number describing the **sample** | Latin: x-bar, s, p-hat | Our sample mean of 323 |\n\n::: {.callout-tip title=\"The whole of inferential statistics in one sentence\"}\nYou can calculate a **statistic**. You want to know a **parameter**. Statistics is\nthe discipline of saying how close the first is likely to be to the second.\n:::\n\nFor teaching purposes we are going to treat our 1,000 transactions as if they were\nthe entire population, then draw samples from them. That lets us see the true answer\nand check whether our methods find it - something you can never do with real data,\nwhich is exactly why simulation is such a good teacher.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrue_mean <- mean(sales$Total)\ntrue_sd   <- sd(sales$Total)\n\ntibble(true_mean = round(true_mean, 2), true_sd = round(true_sd, 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 1 × 2\n#>   true_mean true_sd\n#>       <dbl>   <dbl>\n#> 1      323.    246.\n```\n\n\n:::\n:::\n\n\n# 2. Sampling variation\n\nTake a sample of 50 transactions and compute the mean. Then do it again.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsample_1 <- sample(sales$Total, size = 50)\nsample_2 <- sample(sales$Total, size = 50)\nsample_3 <- sample(sales$Total, size = 50)\n\ntibble(\n  sample = c(\"Sample 1\", \"Sample 2\", \"Sample 3\", \"TRUE POPULATION\"),\n  mean   = round(c(mean(sample_1), mean(sample_2), mean(sample_3), true_mean), 2)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 4 × 2\n#>   sample           mean\n#>   <chr>           <dbl>\n#> 1 Sample 1         352.\n#> 2 Sample 2         312.\n#> 3 Sample 3         337.\n#> 4 TRUE POPULATION  323.\n```\n\n\n:::\n:::\n\n\nThree different samples, three different answers, none of them exactly the true\nvalue. **This is not a mistake. It is the fundamental problem of statistics.**\n\nYour business has one sample. It got one of these numbers. The question is not \"how\ndo I avoid this?\" - you cannot - but \"how far off am I likely to be?\"\n\n# 3. The sampling distribution\n\nIf one sample mean is unreliable, what happens if we look at thousands of them?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsample_means_50 <- replicate(2000, mean(sample(sales$Total, size = 50)))\n\ntibble(\n  mean_of_the_means = round(mean(sample_means_50), 2),\n  true_mean         = round(true_mean, 2),\n  sd_of_the_means   = round(sd(sample_means_50), 2)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 1 × 3\n#>   mean_of_the_means true_mean sd_of_the_means\n#>               <dbl>     <dbl>           <dbl>\n#> 1              322.      323.            33.3\n```\n\n\n:::\n:::\n\n\nTwo remarkable things.\n\n**The average of the sample means lands almost exactly on the true mean.** Individual\nsamples are unreliable, but they are unreliable *symmetrically* - they miss high as\noften as low. The sample mean is an **unbiased** estimator.\n\n**The sample means vary far less than individual transactions do.** The transactions\nhad a standard deviation of about 246; the sample means have one of about 35.\nAveraging cancels out noise.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(sample_mean = sample_means_50) |>\n  ggplot(aes(x = sample_mean)) +\n  geom_histogram(bins = 40, fill = \"#A83296\", colour = \"white\") +\n  geom_vline(xintercept = true_mean, colour = \"#1A1A1A\", linewidth = 1) +\n  labs(title = \"2,000 sample means, each from a sample of 50\",\n       subtitle = \"The solid line is the true population mean\",\n       x = \"Sample mean\", y = \"Frequency\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](3.2-Estimation-and-Confidence-Intervals_files/figure-html/sampling_dist_plot-1.png){width=672}\n:::\n:::\n\n\n# 4. The Central Limit Theorem\n\nLook at that histogram again. It is **bell-shaped** - even though individual\ntransaction totals were clearly right-skewed in section 2.\n\nThat is the Central Limit Theorem, and it is the single most important result in\nstatistics.\n\n::: {.callout-tip title=\"The Central Limit Theorem\"}\nAs the sample size grows, the distribution of the **sample mean** approaches a normal\ndistribution - **regardless of the shape of the original population**.\n\nIts centre is the population mean. Its standard deviation is\n`population sd / sqrt(n)`, which is called the **standard error**.\n:::\n\nThis is why the normal distribution dominates statistics even though real business\ndata is rarely normal. You are almost never modelling individual values. You are\nmodelling an average, and averages become normal even when the things being averaged\nare not.\n\n## Watching it happen\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsample_sizes <- c(2, 5, 30, 100)\n\nclt_data <- map_dfr(sample_sizes, function(size_n) {\n  tibble(\n    n           = paste(\"n =\", size_n),\n    sample_mean = replicate(2000, mean(sample(sales$Total, size = size_n)))\n  )\n}) |>\n  mutate(n = factor(n, levels = paste(\"n =\", sample_sizes)))\n\nggplot(clt_data, aes(x = sample_mean)) +\n  geom_histogram(bins = 40, fill = \"#A83296\", colour = \"white\") +\n  facet_wrap(~ n, scales = \"free\") +\n  labs(title = \"The Central Limit Theorem in action\",\n       subtitle = \"Skewed at n = 2, unmistakably normal by n = 30\",\n       x = \"Sample mean\", y = \"Frequency\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](3.2-Estimation-and-Confidence-Intervals_files/figure-html/clt_demo-1.png){width=672}\n:::\n:::\n\n\nAt `n = 2` the distribution still carries the right skew of the original data. By\n`n = 30` it is convincingly bell-shaped. This is where the common rule of thumb\n\"n of at least 30\" comes from.\n\n::: {.callout-warning title=\"n = 30 is a rule of thumb, not a law\"}\nHow large a sample you need depends on **how skewed the population is**. Mildly\nskewed data is fine at n = 15. Severely skewed data - insurance claims, say, where\none claim can dwarf a thousand others - may need several hundred.\n\nThe honest procedure is to check, not to recite 30.\n:::\n\n## The standard error\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 50\n\ntibble(\n  formula_se  = round(true_sd / sqrt(n), 3),\n  simulated_se = round(sd(sample_means_50), 3)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 1 × 2\n#>   formula_se simulated_se\n#>        <dbl>        <dbl>\n#> 1       34.8         33.3\n```\n\n\n:::\n:::\n\n\nThe formula and the simulation agree. The **standard error** is the standard\ndeviation of the sampling distribution: the typical distance between a sample mean\nand the truth.\n\nNotice the `sqrt(n)`. To halve your uncertainty you must **quadruple** your sample\nsize. This is the single most important practical fact about sampling, and it is why\nsurveys get expensive fast.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(\n  sample_size    = c(10, 25, 50, 100, 400, 1600),\n  standard_error = round(true_sd / sqrt(c(10, 25, 50, 100, 400, 1600)), 2)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 6 × 2\n#>   sample_size standard_error\n#>         <dbl>          <dbl>\n#> 1          10          77.8 \n#> 2          25          49.2 \n#> 3          50          34.8 \n#> 4         100          24.6 \n#> 5         400          12.3 \n#> 6        1600           6.15\n```\n\n\n:::\n:::\n\n\nGoing from 100 to 400 costs four times as much and only halves the error. Going from\n400 to 1600 costs four times again for another halving. There is a point where more\ndata stops being worth the money, and this table is how you find it.\n\n# 5. Confidence intervals for a mean\n\nA single number - \"the average transaction is 323\" - hides all of this uncertainty. A\n**confidence interval** reports a range instead.\n\n## Building one by hand\n\nThe recipe: take your estimate, and go out a certain number of standard errors either\nside.\n\n$$\\bar{x} \\pm t^* \\times \\frac{s}{\\sqrt{n}}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_sample <- sample(sales$Total, size = 50)\n\nx_bar <- mean(my_sample)\ns     <- sd(my_sample)\nn     <- length(my_sample)\nse    <- s / sqrt(n)\n\n# The multiplier for 95 percent confidence, with n - 1 degrees of freedom\nt_star <- qt(0.975, df = n - 1)\n\ntibble(\n  x_bar  = round(x_bar, 2),\n  se     = round(se, 2),\n  t_star = round(t_star, 3),\n  lower  = round(x_bar - t_star * se, 2),\n  upper  = round(x_bar + t_star * se, 2)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 1 × 5\n#>   x_bar    se t_star lower upper\n#>   <dbl> <dbl>  <dbl> <dbl> <dbl>\n#> 1  299.  35.8   2.01  227.  371.\n```\n\n\n:::\n:::\n\n\nThree things to notice about `qt(0.975, df = n - 1)`.\n\n**Why 0.975 and not 0.95?** For a 95 percent interval you leave 5 percent outside,\nsplit as 2.5 percent in each tail. So you want the value with 97.5 percent below it.\n\n**Why the t-distribution rather than the normal?** Because you are using the *sample*\nstandard deviation `s` in place of the unknown population sigma. That substitution\nadds uncertainty, and the t-distribution's slightly fatter tails account for it.\n\n**Why `n - 1`?** These are the degrees of freedom. Once you know the sample mean and\n`n - 1` of the values, the last value is determined - so only `n - 1` pieces of\ninformation are genuinely free.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(\n  sample_size = c(5, 10, 30, 100, 1000),\n  t_multiplier = round(qt(0.975, df = c(5, 10, 30, 100, 1000) - 1), 3),\n  z_multiplier = round(qnorm(0.975), 3)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 5 × 3\n#>   sample_size t_multiplier z_multiplier\n#>         <dbl>        <dbl>        <dbl>\n#> 1           5         2.78         1.96\n#> 2          10         2.26         1.96\n#> 3          30         2.04         1.96\n#> 4         100         1.98         1.96\n#> 5        1000         1.96         1.96\n```\n\n\n:::\n:::\n\n\nThe t multiplier starts large and converges on 1.96 as the sample grows. With small\nsamples you pay a real penalty in interval width; by n = 100 the difference is\nnegligible.\n\n## The one-line version\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(my_sample)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tOne Sample t-test\n#> \n#> data:  my_sample\n#> t = 8.3692, df = 49, p-value = 5.237e-11\n#> alternative hypothesis: true mean is not equal to 0\n#> 95 percent confidence interval:\n#>  227.4594 371.2098\n#> sample estimates:\n#> mean of x \n#>  299.3346\n```\n\n\n:::\n:::\n\n\n`t.test()` does everything above. Read the `95 percent confidence interval` line.\n(The rest of that output is a hypothesis test, which is section 3.3 - ignore it for\nnow.)\n\nTo extract just the interval:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(my_sample)$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 227.4594 371.2098\n#> attr(,\"conf.level\")\n#> [1] 0.95\n```\n\n\n:::\n:::\n\n\nDifferent confidence levels:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(\n  level = c(\"90%\", \"95%\", \"99%\"),\n  lower = c(t.test(my_sample, conf.level = 0.90)$conf.int[1],\n            t.test(my_sample, conf.level = 0.95)$conf.int[1],\n            t.test(my_sample, conf.level = 0.99)$conf.int[1]),\n  upper = c(t.test(my_sample, conf.level = 0.90)$conf.int[2],\n            t.test(my_sample, conf.level = 0.95)$conf.int[2],\n            t.test(my_sample, conf.level = 0.99)$conf.int[2])\n) |>\n  mutate(width = round(upper - lower, 2),\n         lower = round(lower, 2),\n         upper = round(upper, 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 3 × 4\n#>   level lower upper width\n#>   <chr> <dbl> <dbl> <dbl>\n#> 1 90%    239.  359.  120.\n#> 2 95%    227.  371.  144.\n#> 3 99%    203.  395.  192.\n```\n\n\n:::\n:::\n\n\n**Higher confidence means a wider interval.** There is no free lunch: the only way to\nbe more certain of capturing the truth is to claim less about where it is. A 100\npercent confidence interval would run from minus infinity to plus infinity - perfectly\nreliable and perfectly useless.\n\n# 6. What a confidence interval actually means\n\nThis is the most misunderstood idea in the course, and it is worth getting exactly\nright.\n\n::: {.callout-warning title=\"What it does NOT mean\"}\nA 95 percent confidence interval does **not** mean \"there is a 95 percent probability\nthe true mean is in this interval\".\n\nThe true mean is a fixed number. It is either in your interval or it is not. There is\nno probability about it once the interval is calculated.\n:::\n\n::: {.callout-tip title=\"What it DOES mean\"}\nThe **procedure** captures the true mean 95 percent of the time.\n\nIf you repeated the whole exercise - draw a sample, build an interval - a hundred\ntimes, about 95 of your intervals would contain the true value and about 5 would\nmiss.\n\nYou do not know which kind yours is.\n:::\n\n## Demonstrating it\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(99)\n\nci_results <- map_dfr(1:100, function(i) {\n  s  <- sample(sales$Total, size = 50)\n  ci <- t.test(s)$conf.int\n  tibble(\n    run      = i,\n    lower    = ci[1],\n    upper    = ci[2],\n    captured = ci[1] <= true_mean & true_mean <= ci[2]\n  )\n})\n\n# How many of the 100 intervals contained the true mean?\nsum(ci_results$captured)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 96\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(ci_results, aes(y = run, colour = captured)) +\n  geom_segment(aes(x = lower, xend = upper, yend = run), linewidth = 0.5) +\n  geom_vline(xintercept = true_mean, colour = \"#1A1A1A\", linewidth = 0.9) +\n  scale_colour_manual(values = c(\"TRUE\" = \"#A83296\", \"FALSE\" = \"#D64545\"),\n                      name = \"Captured the truth\") +\n  labs(title = \"100 confidence intervals from 100 different samples\",\n       subtitle = \"The vertical line is the true population mean\",\n       x = \"Transaction total\", y = \"Sample number\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](3.2-Estimation-and-Confidence-Intervals_files/figure-html/ci_coverage_plot-1.png){width=672}\n:::\n:::\n\n\nEach horizontal line is one 95 percent confidence interval from one sample. Most\ncross the true mean; a handful, shown in red, miss entirely.\n\n**Those red intervals are not mistakes.** Nothing was done wrong in producing them.\nThey are the 5 percent the method is designed to get wrong, and there is no way to\ntell from the inside which of your intervals is one of them.\n\n# 7. Confidence intervals for a proportion\n\nNot everything is a mean. Often you want a **share**: what percentage of customers\nare members?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmembers <- sum(sales$`Customer type` == \"Member\")\ntotal   <- nrow(sales)\n\ntibble(members, total, proportion = round(members / total, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 1 × 3\n#>   members total proportion\n#>     <int> <int>      <dbl>\n#> 1     501  1000      0.501\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(members, total)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \t1-sample proportions test with continuity correction\n#> \n#> data:  members out of total, null probability 0.5\n#> X-squared = 0.001, df = 1, p-value = 0.9748\n#> alternative hypothesis: true p is not equal to 0.5\n#> 95 percent confidence interval:\n#>  0.4695677 0.5324245\n#> sample estimates:\n#>     p \n#> 0.501\n```\n\n\n:::\n:::\n\n\n`prop.test(successes, trials)` gives the interval directly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(members, total)$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 0.4695677 0.5324245\n#> attr(,\"conf.level\")\n#> [1] 0.95\n```\n\n\n:::\n:::\n\n\nThe interval comfortably includes 0.50, so on this evidence you could not rule out\nthat the chain's customer base is exactly half members - a useful thing to know\nbefore anyone builds a strategy on a supposed imbalance.\n\n## The margin of error\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_hat <- members / total\n\nmoe <- 1.96 * sqrt(p_hat * (1 - p_hat) / total)\n\ntibble(\n  estimate       = round(p_hat, 4),\n  margin_of_error = round(moe, 4),\n  lower          = round(p_hat - moe, 4),\n  upper          = round(p_hat + moe, 4)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 1 × 4\n#>   estimate margin_of_error lower upper\n#>      <dbl>           <dbl> <dbl> <dbl>\n#> 1    0.501           0.031  0.47 0.532\n```\n\n\n:::\n:::\n\n\nThis is the \"plus or minus 3 percentage points\" you see quoted with opinion polls.\nNow you know exactly where that number comes from.\n\n# 8. How big a sample do I need?\n\nTurn the formula around. If you want a margin of error of `E`:\n\n$$n = \\left(\\frac{1.96 \\times \\sigma}{E}\\right)^2$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntarget_errors <- c(50, 25, 10, 5)\n\ntibble(\n  target_margin = target_errors,\n  needed_n      = ceiling((1.96 * true_sd / target_errors)^2)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 4 × 2\n#>   target_margin needed_n\n#>           <dbl>    <dbl>\n#> 1            50       93\n#> 2            25      372\n#> 3            10     2323\n#> 4             5     9291\n```\n\n\n:::\n:::\n\n\nTo estimate average transaction value to within 5 either way, you need a sample of\nseveral thousand. To within 50, a few dozen. **The cost of precision rises as the\nsquare of the precision you demand.**\n\nFor a proportion, the worst case is `p = 0.5`, which makes planning easy:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntarget_moe <- c(0.05, 0.03, 0.02, 0.01)\n\ntibble(\n  target_margin = target_moe,\n  needed_n      = ceiling(1.96^2 * 0.25 / target_moe^2)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 4 × 2\n#>   target_margin needed_n\n#>           <dbl>    <dbl>\n#> 1          0.05      385\n#> 2          0.03     1068\n#> 3          0.02     2401\n#> 4          0.01     9604\n```\n\n\n:::\n:::\n\n\nThat second row is why national opinion polls almost always sample around 1,000\npeople. It is the cheapest sample size that delivers a 3-point margin of error - and\nnotice that it does not depend on the size of the population at all. Polling Jordan\nand polling China need the same sample size for the same precision, which surprises\nalmost everyone.\n\n:::: {.callout-note title=\"Self-check\"}\nA colleague says: \"our survey of 1,000 customers has a 3 percent margin of error, so\nif we surveyed 10,000 the margin would drop to 0.3 percent.\" What is wrong?\n\n::: {.callout-note collapse=\"true\" title=\"Show the answer\"}\nThe margin of error shrinks with the **square root** of the sample size, not with the\nsample size itself.\n\nMultiplying `n` by 10 divides the margin by `sqrt(10)`, which is about 3.16. So the\nmargin would fall from about 3 percent to about 0.95 percent - a real improvement, but\nnothing like the tenfold reduction the colleague expects.\n\nTo actually reach 0.3 percent you would need roughly 100 times the original sample -\nabout 100,000 people.\n\nThis misunderstanding costs real money. Someone who believes error falls linearly\nwith sample size will happily approve a survey ten times larger expecting ten times\nthe precision, and will be disappointed.\n:::\n::::\n\n# Your turn - full exercises\n\n**Exercise 1 - Sampling distribution.**\nDraw 1,000 samples of size 25 from `Rating` and store their means. Report the mean and\nstandard deviation of those sample means, compare the standard deviation with the\ntheoretical standard error, and plot the distribution.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# YOUR CODE HERE\n```\n:::\n\n\n**Exercise 2 - Confidence interval by hand and by function.**\nTake a sample of 80 transactions. Build a 95 percent confidence interval for the mean\n`Total` **by hand** using `qt()`, then confirm it with `t.test()`. Do the two agree?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# YOUR CODE HERE\n```\n:::\n\n\n**Exercise 3 - Confidence level and width.**\nUsing the same sample of 80, build 80, 90, 95 and 99 percent intervals. Produce a\ntable of their widths and write one sentence explaining the pattern.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# YOUR CODE HERE\n```\n:::\n\n\n**Exercise 4 - Proportion.**\nWhat proportion of transactions are paid by credit card? Build a 95 percent confidence\ninterval. Could the true proportion plausibly be one third?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# YOUR CODE HERE\n```\n:::\n\n\n**Exercise 5 - Sample size planning.**\nYour manager wants to estimate the average customer `Rating` to within 0.1 either way,\nwith 95 percent confidence. Using the sample standard deviation of `Rating` as an\nestimate of sigma, how many customers must be surveyed? If each survey costs 2 dinars,\nwhat is the budget - and what would it be for a margin of 0.2 instead?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# YOUR CODE HERE\n```\n:::\n\n\nSolutions are in `3.2-Estimation-and-Confidence-Intervals-SOLUTIONS.Rmd`.\n\n# Reference card\n\n| Code | What it does |\n|---|---|\n| `sample(x, size = n)` | Draw a random sample |\n| `sample(x, size = n, replace = TRUE)` | Draw with replacement (bootstrap) |\n| `replicate(N, expr)` | Repeat an expression N times |\n| `sd(x) / sqrt(n)` | Standard error of the mean |\n| `qt(0.975, df = n - 1)` | t multiplier for a 95 percent interval |\n| `qnorm(0.975)` | z multiplier, 1.96 |\n| `t.test(x)` | Confidence interval for a mean |\n| `t.test(x, conf.level = 0.99)` | A different confidence level |\n| `t.test(x)$conf.int` | Just the interval |\n| `prop.test(successes, trials)` | Confidence interval for a proportion |\n| `ceiling((1.96 * sd / E)^2)` | Sample size for margin of error E |\n\n# Summary\n\n- A **statistic** describes your sample; a **parameter** describes the population. You compute the first to estimate the second.\n- Sample means vary from sample to sample. That variation is the **sampling distribution**.\n- The **Central Limit Theorem** says the sampling distribution of the mean becomes normal as `n` grows, whatever the shape of the population.\n- The **standard error**, `s / sqrt(n)`, is the typical distance from a sample mean to the truth. Halving it requires **quadrupling** the sample.\n- A **confidence interval** reports a range instead of a single number. Use `t.test()` for means, `prop.test()` for proportions.\n- A 95 percent interval means **the procedure** succeeds 95 percent of the time. It does not assign a probability to your particular interval.\n- Higher confidence buys width, not accuracy. Required sample size grows with the **square** of the precision you demand.\n\n**Next:** section 3.3, where you stop estimating a value and start testing a claim\nabout it.\n",
    "supporting": [
      "3.2-Estimation-and-Confidence-Intervals_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}