{
  "hash": "6be9eb0e67a6b53085471c8121999029",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"3.1 Probability Distributions\"\nsubtitle: \"\"\n---\n\n## New R this week\n\nR uses a single naming system for every distribution. Learn it once and you know all\nof them.\n\n| Prefix | Question it answers | Example |\n|---|---|---|\n| `d` | What is the probability of **exactly** this value? | `dbinom(3, 10, 0.2)` |\n| `p` | What is the probability of **this or less**? | `pnorm(500, 323, 245)` |\n| `q` | Which **value** sits at this probability? | `qnorm(0.95, 323, 245)` |\n| `r` | Give me **random** draws from this distribution | `rnorm(100, 323, 245)` |\n\nAttach a prefix to a distribution name: `binom`, `pois`, `norm`, `unif`, `t`.\nSo `pbinom`, `rpois`, `qnorm` and so on. That is 20 functions from one table.\n\n## Objectives\n\nBy the end of this notebook you will be able to:\n\n- Explain what a random variable is, and the difference between discrete and continuous\n- Use the binomial distribution to model counts of successes in a fixed number of trials\n- Use the Poisson distribution to model counts of events in an interval\n- Use the normal distribution to model continuous measurements\n- Convert any value to a z-score and interpret it\n- Read the `d`/`p`/`q`/`r` function family fluently\n- Choose the right distribution for a business situation\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(readxl)\n\nsales <- read_excel(\"../data/supermarket_sales.xlsx\")\n```\n:::\n\n\n# 1. From describing to modelling\n\nSection 2 described the 1,000 transactions you have. This section does something\ndifferent: it builds a **model** of the process that generates transactions, so you\ncan reason about ones you have not seen yet.\n\nThat shift is what makes statistics useful to a business. Describing last month's\nsales is bookkeeping. Saying \"there is a 5 percent chance we run out of stock next\nTuesday\" is planning.\n\nA **random variable** is a numerical outcome of a process whose result is not known\nin advance. Two kinds:\n\n| Type | What it can be | Examples here |\n|---|---|---|\n| **Discrete** | Separate, countable values | `Quantity` (1, 2, 3...), number of complaints |\n| **Continuous** | Any value in a range | `Total`, `Unit price`, time between customers |\n\nThe distinction matters because the two kinds need different mathematics. For\ndiscrete variables you can ask \"what is the probability of exactly 5?\" For\ncontinuous variables that question has no useful answer - the probability of a\ntransaction being exactly 323.0000... is zero - so you ask \"what is the probability\nof between 300 and 350?\" instead.\n\n::: {.callout-tip title=\"A probability distribution\"}\nA probability distribution is a rule that assigns probability to each possible\noutcome of a random variable.\n\nThink of it as the shape a histogram would settle into if you could collect\ninfinitely many observations.\n:::\n\n# 2. The binomial distribution\n\nUse the binomial when you count **how many successes in a fixed number of\nindependent attempts**, each with the same probability of success.\n\nFour conditions must hold:\n\n1. A **fixed number** of trials, called `n`\n2. Each trial has only **two outcomes** - success or failure\n3. The probability of success, `p`, is the **same every time**\n4. Trials are **independent** - one outcome does not affect another\n\n## A business question\n\nAbout half of the chain's customers are members. If 20 customers walk in, what is the\nchance that exactly 12 of them are members?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# First, the actual member rate in our data\np_member <- mean(sales$`Customer type` == \"Member\")\np_member\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 0.501\n```\n\n\n:::\n:::\n\n\nThat line is worth reading carefully. `sales$\\`Customer type\\` == \"Member\"` produces\na column of `TRUE`/`FALSE`. R treats `TRUE` as 1 and `FALSE` as 0, so taking the mean\nof that column gives the **proportion** that are `TRUE`. This is a very common R\nidiom and you will use it constantly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Probability of exactly 12 members out of 20 customers\ndbinom(12, size = 20, prob = p_member)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 0.1210944\n```\n\n\n:::\n:::\n\n\nAbout a 12 percent chance. Now some more useful questions:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 12 or fewer members\npbinom(12, size = 20, prob = p_member)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 0.8664802\n```\n\n\n:::\n\n```{.r .cell-code}\n# More than 12 members (note: 1 minus \"12 or fewer\")\n1 - pbinom(12, size = 20, prob = p_member)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 0.1335198\n```\n\n\n:::\n:::\n\n\n::: {.callout-warning title=\"The off-by-one trap\"}\n`pbinom(12, ...)` means \"12 **or fewer**\", including 12.\n\nSo \"more than 12\" is `1 - pbinom(12, ...)`, **not** `1 - pbinom(13, ...)`. Getting\nthis wrong by one is the most common error with discrete distributions. When in\ndoubt, write out the values you want to include.\n:::\n\n## Seeing the whole distribution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbinom_dist <- tibble(\n  members     = 0:20,\n  probability = dbinom(0:20, size = 20, prob = p_member)\n)\n\nggplot(binom_dist, aes(x = members, y = probability)) +\n  geom_col(fill = \"#A83296\") +\n  labs(title = \"Members among 20 random customers\",\n       subtitle = paste0(\"Binomial, n = 20, p = \", round(p_member, 3)),\n       x = \"Number of members\", y = \"Probability\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](3.1-Probability-Distributions_files/figure-html/binom_plot-1.png){width=672}\n:::\n:::\n\n\nThe distribution peaks at 10, which is what you would expect when half of all\ncustomers are members. Its **mean is n times p**, and its spread is\n`sqrt(n * p * (1 - p))`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 20\ntibble(\n  mean = n * p_member,\n  sd   = sqrt(n * p_member * (1 - p_member))\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 1 × 2\n#>    mean    sd\n#>   <dbl> <dbl>\n#> 1  10.0  2.24\n```\n\n\n:::\n:::\n\n\n:::: {.callout-note title=\"Your turn\"}\nAbout one third of transactions are paid by Ewallet. Out of 15 customers, what is the\nprobability that **fewer than 4** pay by Ewallet?\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_ewallet <- mean(sales$Payment == \"______\")\n\n# \"Fewer than 4\" means 3 or fewer\npbinom(____, size = ____, prob = p_ewallet)\n```\n:::\n\n\n::: {.callout-note collapse=\"true\" title=\"Show the answer\"}\n```r\np_ewallet <- mean(sales$Payment == \"Ewallet\")\npbinom(3, size = 15, prob = p_ewallet)\n```\n\nThe key step is translating \"fewer than 4\" into \"3 or fewer\". `pbinom` always\nincludes the value you give it, so you must subtract one from a strict inequality.\n:::\n::::\n\n# 3. The Poisson distribution\n\nUse the Poisson when you count **how many events occur in a fixed interval** of time\nor space, and there is no natural upper limit.\n\nThe binomial asks \"how many of these 20?\" The Poisson asks \"how many will happen at\nall?\"\n\n| Situation | Distribution |\n|---|---|\n| Of 20 customers, how many are members? | Binomial (there is a maximum of 20) |\n| How many customers arrive in the next hour? | Poisson (no fixed maximum) |\n| Of 50 items shipped, how many are damaged? | Binomial |\n| How many complaints arrive this week? | Poisson |\n\nThe Poisson needs only one number: **lambda**, the average rate of events per\ninterval.\n\n## A business question\n\nThe three branches together handled 1,000 transactions over about 90 days. Suppose a\nbranch averages 4 transactions per hour. Staffing needs to cope with busy hours.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlambda <- 4\n\n# Exactly 6 transactions in an hour\ndpois(6, lambda = lambda)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 0.1041956\n```\n\n\n:::\n\n```{.r .cell-code}\n# 6 or fewer\nppois(6, lambda = lambda)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 0.889326\n```\n\n\n:::\n\n```{.r .cell-code}\n# More than 8 - a genuinely busy hour\n1 - ppois(8, lambda = lambda)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 0.02136343\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npois_dist <- tibble(\n  transactions = 0:15,\n  probability  = dpois(0:15, lambda = lambda)\n)\n\nggplot(pois_dist, aes(x = transactions, y = probability)) +\n  geom_col(fill = \"#A83296\") +\n  labs(title = \"Transactions per hour\",\n       subtitle = \"Poisson, lambda = 4\",\n       x = \"Transactions in one hour\", y = \"Probability\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](3.1-Probability-Distributions_files/figure-html/pois_plot-1.png){width=672}\n:::\n:::\n\n\nNotice the shape is **right-skewed**. There is a hard floor at zero - you cannot have\nnegative transactions - but no ceiling, so the tail runs to the right. This is why\ncount data so often fails a normality check, as you saw in section 2.\n\n::: {.callout-tip title=\"A useful oddity of the Poisson\"}\nFor a Poisson distribution the **mean and the variance are both lambda**.\n\nThat gives you a free diagnostic. If you have count data whose variance is much\nlarger than its mean, a Poisson model is probably wrong - the events are not\noccurring independently, perhaps because they arrive in clusters.\n:::\n\n## Why the shape matters for staffing\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(\n  capacity          = 4:10,\n  prob_overwhelmed  = round(1 - ppois(4:10, lambda = 4), 4)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 7 × 2\n#>   capacity prob_overwhelmed\n#>      <int>            <dbl>\n#> 1        4           0.371 \n#> 2        5           0.215 \n#> 3        6           0.111 \n#> 4        7           0.0511\n#> 5        8           0.0214\n#> 6        9           0.0081\n#> 7       10           0.0028\n```\n\n\n:::\n:::\n\n\nRead that table as a manager. If you staff for the average of 4 transactions an\nhour, you are overwhelmed about 37 percent of the time. Staffing for 8 drops that to\naround 2 percent.\n\nThis is the entire point of probability distributions in business: **planning for the\naverage guarantees you fail about half the time.** You have to plan for the tail.\n\n:::: {.callout-note title=\"Your turn\"}\nA branch receives an average of 2.5 customer complaints per week. What is the\nprobability of a week with **no complaints at all**?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndpois(____, lambda = ____)\n```\n:::\n\n\n::: {.callout-note collapse=\"true\" title=\"Show the answer\"}\n```r\ndpois(0, lambda = 2.5)\n```\n\nAbout 8 percent. A complaint-free week is uncommon but not remarkable - which is\nworth knowing before anyone declares a quality initiative a success on one good\nweek's evidence.\n:::\n::::\n\n# 4. The normal distribution\n\nThe most important continuous distribution. It is symmetric, bell-shaped, and\ndefined by exactly two numbers: the **mean** (where the centre sits) and the\n**standard deviation** (how wide it is).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnorm_demo <- tibble(\n  x = seq(-6, 6, length.out = 400)\n) |>\n  mutate(\n    `SD = 1`   = dnorm(x, mean = 0, sd = 1),\n    `SD = 2`   = dnorm(x, mean = 0, sd = 2),\n    `SD = 0.5` = dnorm(x, mean = 0, sd = 0.5)\n  ) |>\n  pivot_longer(-x, names_to = \"spread\", values_to = \"density\")\n\nggplot(norm_demo, aes(x = x, y = density, colour = spread)) +\n  geom_line(linewidth = 1) +\n  scale_colour_manual(values = c(\"#A83296\", \"#D070D0\", \"#5C1A54\")) +\n  labs(title = \"Three normal distributions with the same mean\",\n       x = \"Value\", y = \"Density\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](3.1-Probability-Distributions_files/figure-html/norm_shapes-1.png){width=672}\n:::\n:::\n\n\nAll three are centred at zero. The standard deviation alone controls how spread out\nthey are.\n\n## The empirical rule\n\nFor any normal distribution:\n\n| Within | Contains about |\n|---|---|\n| 1 standard deviation of the mean | 68 percent of values |\n| 2 standard deviations | 95 percent |\n| 3 standard deviations | 99.7 percent |\n\nVerify it in R rather than taking it on trust:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(\n  within_sd = 1:3,\n  proportion = round(pnorm(1:3) - pnorm(-(1:3)), 4)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 3 × 2\n#>   within_sd proportion\n#>       <int>      <dbl>\n#> 1         1      0.683\n#> 2         2      0.954\n#> 3         3      0.997\n```\n\n\n:::\n:::\n\n\n`pnorm(1) - pnorm(-1)` is \"the area below +1 minus the area below -1\", which is the\narea between them. That is the 68 percent.\n\n## Applying it to the ratings data\n\n`Rating` is not perfectly normal - you saw that in section 2 - but it is symmetric\nenough to illustrate the method.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr_mean <- mean(sales$Rating)\nr_sd   <- sd(sales$Rating)\n\ntibble(mean = round(r_mean, 3), sd = round(r_sd, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 1 × 2\n#>    mean    sd\n#>   <dbl> <dbl>\n#> 1  6.97  1.72\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# What proportion of customers should rate us below 5, if ratings were normal?\npnorm(5, mean = r_mean, sd = r_sd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 0.1255119\n```\n\n\n:::\n\n```{.r .cell-code}\n# What proportion actually did?\nmean(sales$Rating < 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 0.153\n```\n\n\n:::\n:::\n\n\nThe model's prediction and the reality differ. That gap is the model being imperfect,\nand noticing it is more valuable than the calculation itself. A model is a\nsimplification you adopt deliberately, not a truth you discover.\n\n## Going the other way with qnorm\n\n`pnorm` takes a value and returns a probability. `qnorm` does the reverse.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Which rating do the bottom 10 percent of customers fall below?\nqnorm(0.10, mean = r_mean, sd = r_sd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 4.770251\n```\n\n\n:::\n\n```{.r .cell-code}\n# Which rating marks the top 5 percent?\nqnorm(0.95, mean = r_mean, sd = r_sd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 9.799513\n```\n\n\n:::\n:::\n\n\nThis is how you set thresholds. \"Flag any customer rating in the bottom 10 percent\nfor follow-up\" becomes an actual number you can put in a report.\n\n# 5. Z-scores and the standard normal\n\nA **z-score** answers: how many standard deviations is this value from the mean?\n\n$$z = \\frac{x - \\mu}{\\sigma}$$\n\nIt converts any normal distribution into the **standard normal** - mean 0, standard\ndeviation 1 - which is what the printed z-tables in your course folder tabulate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# A customer who left a rating of 9. How unusual is that?\nz <- (9 - r_mean) / r_sd\nz\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 1.179636\n```\n\n\n:::\n:::\n\n\nA z-score of about 1.2 means this rating sits 1.2 standard deviations above average.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# What proportion of customers rate us 9 or lower?\npnorm(z)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 0.8809276\n```\n\n\n:::\n\n```{.r .cell-code}\n# So what proportion rate us above 9?\n1 - pnorm(z)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 0.1190724\n```\n\n\n:::\n:::\n\n\n::: {.callout-tip title=\"Why z-scores exist\"}\nThey make **incomparable things comparable**.\n\nA student scoring 78 on a maths exam and 84 on a history exam has done better in\nhistory - unless the maths exam was much harder. Convert both to z-scores and you can\nsay which performance was more impressive *relative to everyone else who sat the same\npaper*.\n\nThe same logic lets you compare a branch's sales performance with its customer\nsatisfaction performance, even though one is measured in currency and the other on a\n1-to-10 scale.\n:::\n\n## Standardising a whole column\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsales_z <- sales |>\n  mutate(\n    total_z  = (Total - mean(Total)) / sd(Total),\n    rating_z = (Rating - mean(Rating)) / sd(Rating)\n  )\n\nsales_z |>\n  select(`Invoice ID`, Total, total_z, Rating, rating_z) |>\n  arrange(desc(total_z)) |>\n  head(5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 5 × 5\n#>   `Invoice ID` Total total_z Rating rating_z\n#>   <chr>        <dbl>   <dbl>  <dbl>    <dbl>\n#> 1 860-79-0874  1043.    2.93    6.6   -0.217\n#> 2 687-47-8271  1039.    2.91    8.7    1.01 \n#> 3 283-26-5248  1034.    2.89    4.5   -1.44 \n#> 4 751-41-9720  1024.    2.85    8      0.598\n#> 5 303-96-2227  1022.    2.84    4.4   -1.50\n```\n\n\n:::\n:::\n\n\nR has a built-in shortcut, `scale()`, though it returns a matrix rather than a plain\ncolumn, so the explicit version above is clearer while you are learning.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# A standardised column always has mean 0 and sd 1\ntibble(\n  mean_z = round(mean(sales_z$total_z), 10),\n  sd_z   = sd(sales_z$total_z)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 1 × 2\n#>   mean_z  sd_z\n#>    <dbl> <dbl>\n#> 1      0     1\n```\n\n\n:::\n:::\n\n\n::: {.callout-warning title=\"Standardising does not make data normal\"}\nConverting to z-scores **shifts and rescales** a distribution. It does not change its\nshape.\n\n`Total` was right-skewed in section 2, and `total_z` is exactly as right-skewed.\nStudents frequently assume standardising fixes non-normality. It does not, and no\namount of z-scoring will make a skewed variable bell-shaped.\n:::\n\n## Using z-scores to find unusual transactions\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsales_z |>\n  filter(abs(total_z) > 2.5) |>\n  select(`Invoice ID`, Branch, `Product line`, Total, total_z) |>\n  arrange(desc(total_z))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 17 × 5\n#>    `Invoice ID` Branch `Product line`         Total total_z\n#>    <chr>        <chr>  <chr>                  <dbl>   <dbl>\n#>  1 860-79-0874  C      Fashion accessories    1043.    2.93\n#>  2 687-47-8271  A      Fashion accessories    1039.    2.91\n#>  3 283-26-5248  C      Food and beverages     1034.    2.89\n#>  4 751-41-9720  C      Home and lifestyle     1024.    2.85\n#>  5 303-96-2227  B      Home and lifestyle     1022.    2.84\n#>  6 744-16-7898  B      Home and lifestyle     1022.    2.84\n#>  7 271-88-8734  C      Fashion accessories    1021.    2.84\n#>  8 234-65-2137  C      Home and lifestyle     1004.    2.77\n#>  9 554-42-2417  C      Sports and travel      1002.    2.76\n#> 10 325-77-6186  A      Home and lifestyle      952.    2.56\n#> 11 280-17-4359  C      Health and beauty       950.    2.55\n#> 12 219-22-9386  B      Sports and travel       945.    2.53\n#> 13 702-83-5291  C      Fashion accessories     943.    2.52\n#> 14 731-81-9469  C      Sports and travel       943.    2.52\n#> 15 817-69-8206  B      Electronic accessories  942.    2.52\n#> 16 393-65-2792  C      Food and beverages      940.    2.51\n#> 17 751-69-0068  C      Sports and travel       938.    2.50\n```\n\n\n:::\n:::\n\n\n`abs()` takes the absolute value, so this catches unusually large *and* unusually\nsmall values in one condition.\n\nThis is a second outlier rule to sit alongside the 1.5 x IQR rule from section 2.\nThey disagree sometimes, and neither is authoritative - the z-score rule is pulled\naround by the very outliers it is trying to find, because extreme values inflate the\nstandard deviation used to compute it.\n\n# 6. Choosing the right distribution\n\nThis is the part that matters in practice, and the part exams test.\n\n| If you are counting... | And... | Use |\n|---|---|---|\n| Successes in a fixed number of trials | Each trial is independent, same probability | **Binomial** |\n| Events in an interval of time or space | No fixed maximum, constant average rate | **Poisson** |\n| A continuous measurement | Symmetric, most values near the centre | **Normal** |\n| Any outcome equally likely in a range | No value preferred | **Uniform** |\n\nSome worked judgements:\n\n- *Of 200 emails sent, how many are opened?* Fixed number, two outcomes, roughly constant probability. **Binomial.**\n- *How many customers enter the shop between 2pm and 3pm?* Counting events in an interval, no maximum. **Poisson.**\n- *What will tomorrow's total revenue be?* A continuous amount built from many independent transactions. **Normal** is a reasonable first model.\n- *How many defective units in a batch of 500?* Fixed number of trials. **Binomial.**\n- *How many machine breakdowns this month?* Events in an interval. **Poisson.**\n\n:::: {.callout-note title=\"Self-check\"}\nA call centre wants to model how many calls arrive between 9am and 10am. A colleague\nsuggests using a binomial distribution \"because each minute either has a call or does\nnot\". What is wrong with that reasoning?\n\n::: {.callout-note collapse=\"true\" title=\"Show the answer\"}\nTwo things.\n\nFirst, **a minute can contain more than one call.** The binomial requires each trial\nto be a clean success or failure, but \"this minute had 3 calls\" breaks that.\n\nSecond, and more fundamentally, **there is no fixed number of trials.** You could\nslice the hour into minutes, or seconds, or milliseconds, and the answer should not\ndepend on how finely you chop up time. That the model changes when you change an\narbitrary choice is a sign the model is wrong.\n\nThe Poisson distribution is precisely the limit of the binomial as the trials get\ninfinitely small and numerous, which is why it is the right tool for events in\ncontinuous time.\n:::\n::::\n\n# 7. Simulation - checking your reasoning\n\nThe `r` functions generate random draws. This lets you verify an answer you worked\nout with formulas, which is the single best habit you can build in this course.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2024)\n\n# Simulate 10,000 groups of 20 customers each\nsimulated <- rbinom(10000, size = 20, prob = p_member)\n\n# How often were exactly 12 members?\nmean(simulated == 12)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 0.12\n```\n\n\n:::\n\n```{.r .cell-code}\n# Compare with the exact formula\ndbinom(12, size = 20, prob = p_member)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 0.1210944\n```\n\n\n:::\n:::\n\n\nThe two agree to about two decimal places. If they had not, one of them would be\nwrong, and you would know to look again.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(members = simulated) |>\n  ggplot(aes(x = members)) +\n  geom_bar(fill = \"#A83296\") +\n  labs(title = \"10,000 simulated groups of 20 customers\",\n       x = \"Number of members in the group\", y = \"Frequency\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](3.1-Probability-Distributions_files/figure-html/sim_plot-1.png){width=672}\n:::\n:::\n\n\n::: {.callout-tip title=\"set.seed()\"}\nRandom numbers in R are **reproducibly** random. `set.seed(2024)` fixes the starting\npoint, so you and your classmates get identical results from the same code.\n\nAlways set a seed in work you will hand in. An analysis nobody can reproduce - not\neven you, tomorrow - is not an analysis.\n:::\n\n# Your turn - full exercises\n\n**Exercise 1 - Binomial.**\nHistorically 30 percent of customers buy a product from the Health and beauty line.\nOut of the next 25 customers:\n\na. What is the probability that exactly 8 buy from that line?\nb. What is the probability that 10 or more do?\nc. What is the expected number, and the standard deviation?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# YOUR CODE HERE\n```\n:::\n\n\n**Exercise 2 - Poisson.**\nA branch averages 3 refund requests per day.\n\na. What is the probability of a day with exactly 5 refund requests?\nb. What is the probability of a day with more than 6?\nc. Produce a table showing, for daily capacities of 3 through 9, the probability of being overwhelmed. What capacity would you recommend and why?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# YOUR CODE HERE\n```\n:::\n\n\n**Exercise 3 - Normal.**\nUsing the actual mean and standard deviation of `Total`:\n\na. What proportion of transactions should exceed 800, if totals were normal?\nb. What proportion actually do?\nc. Explain the gap. Which section 2 finding predicts it?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# YOUR CODE HERE\n```\n:::\n\n\n**Exercise 4 - Z-scores.**\nFind the transaction with the highest `Total`. Compute its z-score and state in one\nsentence how unusual it is. Then compute the z-score of the highest `Rating` and say\nwhich of the two is the more extreme observation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# YOUR CODE HERE\n```\n:::\n\n\n**Exercise 5 - Choose and justify.**\nFor each situation, name the distribution and justify it in one sentence:\n\na. Number of items in a customer's basket\nb. Number of customers who abandon a queue in an hour\nc. Total revenue on a randomly chosen day\nd. Number of the next 40 online orders that are returned\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# YOUR CODE HERE - and write your reasoning as comments\n```\n:::\n\n\nSolutions are in `3.1-Probability-Distributions-SOLUTIONS.Rmd`.\n\n# Reference card\n\n| Code | What it does |\n|---|---|\n| `dbinom(k, n, p)` | P(exactly k successes) |\n| `pbinom(k, n, p)` | P(k or fewer successes) |\n| `1 - pbinom(k, n, p)` | P(more than k successes) |\n| `rbinom(N, n, p)` | N random binomial draws |\n| `dpois(k, lambda)` | P(exactly k events) |\n| `ppois(k, lambda)` | P(k or fewer events) |\n| `rpois(N, lambda)` | N random Poisson draws |\n| `dnorm(x, mean, sd)` | Height of the normal curve at x |\n| `pnorm(x, mean, sd)` | P(value is x or less) |\n| `qnorm(p, mean, sd)` | The value below which p of the data falls |\n| `rnorm(N, mean, sd)` | N random normal draws |\n| `(x - mean(x)) / sd(x)` | Convert to z-scores |\n| `mean(vec == \"A\")` | Proportion of a column equal to \"A\" |\n| `set.seed(2024)` | Make random results reproducible |\n\n# Summary\n\n- A **random variable** is a numerical outcome of an uncertain process; it is either **discrete** or **continuous**.\n- The **binomial** counts successes in a fixed number of independent trials.\n- The **Poisson** counts events in an interval with no fixed maximum; its mean equals its variance.\n- The **normal** models continuous measurements and needs only a mean and a standard deviation.\n- The **empirical rule** - 68, 95, 99.7 percent within 1, 2, 3 standard deviations - is worth memorising.\n- A **z-score** expresses a value as a distance in standard deviations, making unlike things comparable. It does not change the shape of the distribution.\n- R's `d`/`p`/`q`/`r` prefixes work identically for every distribution.\n- **Simulate to check your formulas.** If the two disagree, one of them is wrong.\n\n**Next:** section 3.2, where you use these distributions to put a margin of error\naround an estimate.\n",
    "supporting": [
      "3.1-Probability-Distributions_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}