{
  "hash": "60bff3e2e9da2e79dd43581c59fa8857",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"3.2 Estimation and Confidence Intervals - Solutions\"\nsubtitle: \"307102 Descriptive Statistics for Business | University of Petra\"\ncode-fold: true\ncode-summary: \"Show the code\"\n---\n\n::: {.callout-caution title=\"Instructor copy\"}\nEvery chunk runs. Results involving `sample()` vary between runs unless a seed is\nset; quoted figures come from `set.seed(2024)`.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(readxl)\n\nset.seed(2024)\n\nsales <- read_excel(\"../data/supermarket_sales.xlsx\")\n\ntrue_mean <- mean(sales$Total)\ntrue_sd   <- sd(sales$Total)\n```\n:::\n\n\n# Inline exercises\n\n## Section 8 - The square root misunderstanding\n\nCovered in the student notebook. The point to land: **margin of error scales with\n`1/sqrt(n)`**, so tenfold more data gives about a 3.16-fold improvement, not tenfold.\n\nWorth putting on the board:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(\n  n              = c(1000, 4000, 10000, 100000),\n  margin_percent = round(1.96 * sqrt(0.25 / c(1000, 4000, 10000, 100000)) * 100, 2)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 4 × 2\n#>        n margin_percent\n#>    <dbl>          <dbl>\n#> 1   1000           3.1 \n#> 2   4000           1.55\n#> 3  10000           0.98\n#> 4 100000           0.31\n```\n\n\n:::\n:::\n\n\n**Why this matters commercially.** Someone who believes error falls linearly with\nsample size will approve a survey ten times larger expecting ten times the precision.\nThat is a real budget decision made on a false premise, and it happens often.\n\n# Exercise 1 - Sampling distribution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsample_means <- replicate(1000, mean(sample(sales$Rating, size = 25)))\n\ntibble(\n  mean_of_means   = round(mean(sample_means), 4),\n  true_mean       = round(mean(sales$Rating), 4),\n  sd_of_means     = round(sd(sample_means), 4),\n  theoretical_se  = round(sd(sales$Rating) / sqrt(25), 4)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 1 × 4\n#>   mean_of_means true_mean sd_of_means theoretical_se\n#>           <dbl>     <dbl>       <dbl>          <dbl>\n#> 1          6.98      6.97       0.343          0.344\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(sample_mean = sample_means) |>\n  ggplot(aes(x = sample_mean)) +\n  geom_histogram(bins = 40, fill = \"#A83296\", colour = \"white\") +\n  geom_vline(xintercept = mean(sales$Rating), colour = \"#1A1A1A\", linewidth = 1) +\n  labs(title = \"1,000 sample means of Rating, each from a sample of 25\",\n       x = \"Sample mean rating\", y = \"Frequency\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](3.2-Estimation-and-Confidence-Intervals-SOLUTIONS_files/figure-html/sol_ex1_plot-1.png){width=672}\n:::\n:::\n\n\n**Expected results.** The mean of the sample means lands within about 0.01 of the true\nmean of 6.97. The simulated standard deviation is close to the theoretical standard\nerror of about 0.34.\n\n**The teaching point students miss.** `Rating` was **not** normal in section 2 - it was\nflat and bounded, with strongly negative excess kurtosis. Yet the distribution of its\nsample means is convincingly bell-shaped.\n\nThat is the Central Limit Theorem doing exactly what it promises, on a population that\nlooks nothing like a bell curve. Ask the class to compare this histogram with the\nhistogram of raw `Rating` from section 2. The contrast makes the theorem concrete in a\nway the formal statement never does.\n\n**Marking guidance.** Full credit needs the comparison between the simulated standard\ndeviation and the theoretical standard error. Students who produce the histogram\nwithout checking that the two agree have done the mechanics without the verification,\nwhich is the habit this course is trying to build.\n\n# Exercise 2 - Confidence interval by hand and by function\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2024)\nmy_sample <- sample(sales$Total, size = 80)\n\nx_bar  <- mean(my_sample)\ns      <- sd(my_sample)\nn      <- length(my_sample)\nse     <- s / sqrt(n)\nt_star <- qt(0.975, df = n - 1)\n\nby_hand <- c(x_bar - t_star * se, x_bar + t_star * se)\n\nby_function <- as.numeric(t.test(my_sample)$conf.int)\n\ntibble(\n  method = c(\"By hand\", \"t.test()\"),\n  lower  = round(c(by_hand[1], by_function[1]), 4),\n  upper  = round(c(by_hand[2], by_function[2]), 4)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 2 × 3\n#>   method   lower upper\n#>   <chr>    <dbl> <dbl>\n#> 1 By hand   279.  395.\n#> 2 t.test()  279.  395.\n```\n\n\n:::\n:::\n\n\n**They agree to the last decimal place**, because `t.test()` computes exactly this\nformula.\n\n**Why this exercise exists.** Students who only ever call `t.test()` treat it as\nmagic, and cannot debug it when the answer looks wrong. Doing it once by hand\nconverts the function from an oracle into a shortcut.\n\n**Marking guidance.** Common errors, in order of frequency:\n\n1. Using `qt(0.95, ...)` instead of `qt(0.975, ...)` - forgetting the interval is\n   two-tailed. This is the most common by a wide margin.\n2. Using `df = n` instead of `df = n - 1`.\n3. Dividing by `n` instead of `sqrt(n)` in the standard error.\n4. Using `qnorm()` instead of `qt()`. At n = 80 this barely changes the answer, which\n   makes it a good moment to ask *when* it would matter - and the answer is small\n   samples.\n\n# Exercise 3 - Confidence level and width\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlevels <- c(0.80, 0.90, 0.95, 0.99)\n\nmap_dfr(levels, function(lv) {\n  ci <- t.test(my_sample, conf.level = lv)$conf.int\n  tibble(\n    level = paste0(lv * 100, \"%\"),\n    lower = round(ci[1], 2),\n    upper = round(ci[2], 2),\n    width = round(ci[2] - ci[1], 2)\n  )\n})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 4 × 4\n#>   level lower upper width\n#>   <chr> <dbl> <dbl> <dbl>\n#> 1 80%    300.  375.  75.3\n#> 2 90%    289.  386.  97  \n#> 3 95%    279.  395. 116. \n#> 4 99%    260.  414. 154.\n```\n\n\n:::\n:::\n\n\n**Expected pattern.** Width increases monotonically with confidence level, and the\nincrease **accelerates** - the step from 95 to 99 percent costs far more width than\nthe step from 80 to 90.\n\n**Model sentence.**\n\n> Higher confidence produces a wider interval, because the only way to be more certain\n> of capturing the true mean is to make a less specific claim about where it is. The\n> cost accelerates: going from 95 to 99 percent confidence widens the interval by more\n> than going from 80 to 90 does, because you are buying coverage from the increasingly\n> thin tails of the distribution.\n\n**Discussion prompt.** Ask what a 100 percent confidence interval would look like. The\nanswer - minus infinity to plus infinity - makes the trade-off unforgettable. Perfect\nreliability and zero information are the same thing.\n\n# Exercise 4 - Proportion\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncredit <- sum(sales$Payment == \"Credit card\")\ntotal  <- nrow(sales)\n\ntibble(credit, total, proportion = round(credit / total, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 1 × 3\n#>   credit total proportion\n#>    <int> <int>      <dbl>\n#> 1    311  1000      0.311\n```\n\n\n:::\n\n```{.r .cell-code}\nprop.test(credit, total)$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 0.2825931 0.3408786\n#> attr(,\"conf.level\")\n#> [1] 0.95\n```\n\n\n:::\n:::\n\n\n**Expected results.** 311 of 1,000 transactions, a proportion of 0.311, with a 95\npercent interval of roughly 0.283 to 0.341.\n\n**The answer to the question:** one third is 0.3333, which **falls inside** the\ninterval. So yes - the true proportion could plausibly be exactly one third. The data\ndoes not rule it out.\n\n**Marking guidance.** The interpretation is the mark. Look for the student explicitly\nchecking whether 0.3333 lies between the bounds, and stating the conclusion in terms\nof plausibility rather than proof.\n\nWatch for the reverse error: a student concluding the proportion **is** one third.\nThe interval is consistent with one third, but equally consistent with 0.29 or 0.34.\nFailing to rule something out is not the same as establishing it - a distinction that\nbecomes central in the next section.\n\n# Exercise 5 - Sample size planning\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsigma <- sd(sales$Rating)\nsigma\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 1.71858\n```\n\n\n:::\n\n```{.r .cell-code}\nn_for <- function(E) ceiling((1.96 * sigma / E)^2)\n\ntibble(\n  margin_of_error = c(0.05, 0.1, 0.2, 0.5),\n  needed_n        = n_for(c(0.05, 0.1, 0.2, 0.5)),\n  cost_dinars     = n_for(c(0.05, 0.1, 0.2, 0.5)) * 2\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 4 × 3\n#>   margin_of_error needed_n cost_dinars\n#>             <dbl>    <dbl>       <dbl>\n#> 1            0.05     4539        9078\n#> 2            0.1      1135        2270\n#> 3            0.2       284         568\n#> 4            0.5        46          92\n```\n\n\n:::\n:::\n\n\n**Expected results.** With `sigma` of about 1.719, a margin of 0.1 needs **1,135**\nrespondents costing **2,270 dinars**. A margin of 0.2 needs **284** respondents\ncosting **568 dinars**.\n\n**The finding worth stating plainly:** **doubling the acceptable margin cuts the cost\nto a quarter.**\n\n**Marking guidance.** The arithmetic is easy; the recommendation is the exercise. A\nstrong answer challenges the specification rather than merely costing it:\n\n> A margin of 0.1 on a 1-to-10 rating scale costs about 2,270 dinars. Relaxing the\n> target to 0.2 costs about 568 - a saving of roughly 1,700 dinars. Since the observed\n> differences in average rating between branches and product lines are themselves only\n> around 0.2 to 0.3, a margin of 0.1 is finer than any decision we would actually make\n> on this data. I would recommend the 0.2 target and spend the difference elsewhere.\n\nThat answer connects the statistical requirement to the business decision, which is\nthe whole point of sample size planning. A student who computes 1,140 and stops has\ndone the sum but not the thinking.\n\n::: {.callout-caution title=\"A caveat worth mentioning\"}\nThis calculation uses the sample standard deviation as if it were the population\nsigma, which is circular - you would not know it before running the survey.\n\nIn practice you take sigma from a pilot study, from historical data, or from a\npublished figure for a similar measure. Mentioning this stops the sharper students\nfrom thinking they have spotted a flaw, and introduces the idea of a pilot study at no\nextra cost.\n:::\n\n# Teaching notes\n\n**Where students get stuck.**\n\n1. **The interpretation of a confidence interval.** Expect the \"95 percent probability\n   the mean is in here\" phrasing repeatedly, including from students who can recite the\n   correct version. The coverage plot in section 6 is the most effective remedy - run\n   it live and let them count the red intervals.\n2. **`qt(0.975)` versus `qt(0.95)`.** Draw the two tails on the board every time.\n3. **Confusing the standard deviation with the standard error.** The one-line\n   distinction that works: *the standard deviation describes the data; the standard\n   error describes the estimate.*\n4. **Believing a bigger population needs a bigger sample.** The polling example in\n   section 8 is the fastest cure. Sample size depends on the variability of the thing\n   measured and the precision you want, not on how many people exist.\n\n**Timing.** Sections 1 to 4 fill one 90-minute session and are the conceptual core.\nSections 5 to 8 fill a second and are more procedural. If pressed, section 8 can be\nset as reading, but do not cut section 6 - the interpretation of a confidence interval\nis the single most examinable idea in the notebook.\n\n**A demonstration worth the five minutes.** Before showing any theory, have the class\neach draw a sample of 20 from the data and write their sample mean on the board. The\nspread of thirty different answers to the same question makes the sampling\ndistribution real in a way no simulation quite matches, because the numbers are\ntheirs.\n\n**Connecting to the Excel track.** `CONFIDENCE.T(alpha, sd, n)` returns the margin of\nerror, which you then add and subtract manually; `t.test()` returns the finished\ninterval. `T.INV.2T(0.05, df)` is `qt(0.975, df)`. Excel has no direct equivalent of\n`prop.test()`, which is one of the clearer wins for R in this section.\n",
    "supporting": [
      "3.2-Estimation-and-Confidence-Intervals-SOLUTIONS_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}